### ISSUE TITLE
After validation merge pull request from hikmat to vagrant-ubuntu for 12

### ISSUE THREAD

**Issue by smorin** [DemandCube/NeverwinterDP_Legacy#10]
https://github.com/DemandCube/vagrant-ubuntu/pull/1

**Comment by noitcudni** [comment]
How do I reject a pull reject. I tried closing it, but it wouldn't let me.

**Comment by noitcudni** [comment]
I committed my changes to master.

**Comment by smorin** [comment]
Which pull request do you want to close?

**Comment by noitcudni** [comment]
https://github.com/DemandCube/vagrant-ubuntu/pull/1 <-- this one.
