### ISSUE TITLE
Test and Review Pull Request of developer-setup on Ubuntu

### ISSUE THREAD

**Issue by smorin** [DemandCube/NeverwinterDP_Legacy#104]
https://github.com/DemandCube/developer-setup/pull/4

Test that the pull request works.
Comment as necessary if it works then let me know so I can merge it in.

**Comment by louzar** [comment]
I found this error 
vboxdrv: unrecognized service

/opt/vagrant/embedded/lib/ruby/2.0.0/tmpdir.rb:34:in `tmpdir': could not find a temporary directory (ArgumentError)
        from /opt/vagrant/embedded/lib/ruby/2.0.0/tmpdir.rb:105:in`tmpdir'
        from /opt/vagrant/embedded/lib/ruby/2.0.0/tmpdir.rb:137:in `create'
        from /opt/vagrant/embedded/lib/ruby/2.0.0/tmpdir.rb:85:in`mktmpdir'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.5.0/lib/vagrant/bundler.rb:50:in `init!'
        from /opt/vagrant/bin/../embedded/gems/gems/vagrant-1.5.0/lib/vagrant/pre-rubygems.rb:22:in`<main>'

**Comment by louzar** [comment]
I noticied that  virtual box and vagrant were not installed

**Comment by smorin** [comment]
@mehikmat We are getting error with the work you did on developer-setup.  Did you get this error when you did your testing?  Can you possibly help Nizar with this?  What version of Ubuntu are you using?

@louzar I haven't seen this error before.  Can you please work with Hikmat to track this down.  What version of Ubuntu are you using?

@louzar when you find the bugs, please comment and ask @mehikmat to fix those bugs and let you know when they are fixed.

**Comment by louzar** [comment]
@mehikmat  My ubuntu version is 12.04

**Comment by louzar** [comment]
@mehikmat I also found another bug, the Current Vagrant Version is not displayed. 
here what I got :
INSTALLED: [ Vagrant ]

version_compare.py requires two arguments
Current Vagrant Version: 
Required Vagrant Version: 1.4.3

**Comment by smorin** [comment]
Have you been able to fix any of the bugs you found?

**Comment by mehikmat** [comment]
@louzar developer-setup was supposed  and I had tested to work on Ubuntu 12.04/13.04 64-bit and CentOS 6.4/6.5 64-bit. So what's your machine architecture. Possibly think you are testing on 32-bit machine right?

**Comment by mehikmat** [comment]
Current Script doesn't support 32-bit OS

**Comment by mehikmat** [comment]
@smorin What to do?. Do we need to add support for 32-bit OSs or it's fine for 64-bit as of now.I had talked with @louzar last time and knew that he is using 32 bit OS

**Comment by mehikmat** [comment]
@louzar I added support for 32-bit Ubuntu
Please get updates and proceed

**Comment by smorin** [comment]
Which vm's did you test on? And which can I shutdown?

**Comment by louzar** [comment]
ok I will test it tomorow

**Comment by mehikmat** [comment]
@smorin I used these two machines to test
ubuntu-12-x32-n1    128.199.232.36
and
ubuntu-13-x32-n1 128.199.228.208

**Comment by smorin** [comment]
Okay are you using and testing with the rest of the machines or can I shut
them down?

On Tue, Apr 8, 2014 at 9:11 PM, Hikmat Dhamee notifications@github.comwrote:

> @smorin https://github.com/smorin I used these two machines to test
> ubuntu-12-x32-n1 128.199.232.36
> and
> ubuntu-13-x32-n1 128.199.228.208
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/DemandCube/NeverwinterDP/issues/104#issuecomment-39927131
> .

## 

Steve Morin | Hacker, Entrepreneur, Startup Advisor
twitter.com/SteveMorin | stevemorin.com
_Live the dream start a startup. Make the world ... a better place._

**Comment by louzar** [comment]
test is ok on my machine

**Comment by mehikmat** [comment]
@smorin I am not using rest of the machines. You can shut them down

**Comment by smorin** [comment]
@mehikmat thanks!
