### ISSUE TITLE
developer-setup - automated unit tests.

### ISSUE THREAD

**Issue by smorin** [DemandCube/NeverwinterDP_Legacy#106]
Develop a separate unit test script that validates that this works.  This should work on a Mac and Ubuntu.  Look at the sections in the parent script on how to test for a Mac.  Make sure the scripts work on ubuntu.  I'll do the final testing on a mac.

**Comment by KingOfPoptart** [comment]
These should not be separate unit tests.  These should be incorporated into https://github.com/DemandCube/QA-NeverwinterDP/tree/master/installation_tests

There is already a configuration for developersetup https://github.com/DemandCube/QA-NeverwinterDP/blob/master/installation_tests/test_configs/developerSetup_config.py

developerSetup_config.py and its roles might need updating for the updated versions.

**Comment by louzar** [comment]
is this the same as https://github.com/DemandCube/NeverwinterDP/issues/93 ?

**Comment by KingOfPoptart** [comment]
Yeah, closing this.
