### ISSUE TITLE
Develop a utility to print out all kafka JMX Metrics and their keys

### ISSUE THREAD

**Issue by anthonyms** [DemandCube/NeverwinterDP_Legacy#107]
Develop a Utility to print out all kafka jmx metrics.

The following links may be useful
https://kafka.apache.org/documentation.html#monitoring
http://metrics.codahale.com/manual/core/

Parent is task 4 on #56

**Comment by anthonyms** [comment]
labels: demandspike, monitoring
Assignee: @mjuaji

**Comment by smorin** [comment]
Great!
