### ISSUE TITLE
Weekly Project Summary Report Generator from Github API

### ISSUE THREAD

**Issue by smorin** [DemandCube/NeverwinterDP_Legacy#108]
We want a report of issues, opened, issues closed, pull requests opened and closed during the past week and by whom.

Using Spark Framework (http://www.sparkjava.com/) and Github API (https://developer.github.com/v3/)

The work should be saved in:
https://github.com/DemandCube/github-reporter

For build tools use Gradle not maven

Create a web app that will generate a report that lists the following:

As far as solution to keep state from the previous week, you can either use mysql or create files to keep state for week.  I leave it up to you to plan out.

Create tickets for:
  (Create additional tickets as necessary)
1) Planning
2) Development
3) Demo to the Team
4) Ansible Scripts to Deploy - DemandCubePlaybooks
5) Unit Tests
6) Ansible Deployment Tests
7) DemandCube Specific Tests

DemandCube Summary:
Issues - Opened [#] , Closed [#] | Pull Requests - Opened [#] , Merged [#]

Team Summary:
Team Member Name: Issues - Opened [#] , Closed [#] | Pull Requests - Opened [#] , Merged [#]

Repo Summary
Repo Name: Issues - Opened [#] , Closed [#] | Pull Requests - Opened [#] , Merged [#]

Issues Opened (Sorted by Repo, Team Member, Issue #) 
Repo Name - Team Member Name: Issue # "Issue Title" -> Link to Issue

Issues Closed (Sorted by Repo, Team Member, Issue #) 
Repo Name - Team Member Name: Issue # "Issue Title" -> Link to Issue

Pull Request Opened (Sorted by Repo, Team Member, Pull Request #) 
Repo Name - Pull Request Issuer: Pull Request # "Pull Request Title" -> Link to Pull Request

Pull Request Closed (Sorted by Repo, Team Member, Pull Request #) 
Repo Name - Pull Request Issuer: Pull Request # "Pull Request Title" -> Link to Pull Request

All Open Pull Requests (Sorted by Repo, Team Member, Pull Request #) 
Repo Name - Pull Request Issuer: Pull Request # "Pull Request Title" -> Link to Pull Request

**Comment by anthonyms** [comment]
Code will live in https://github.com/DemandCube/github-reporter

**Comment by anthonyms** [comment]
Pull request URL 
https://github.com/DemandCube/github-reporter/pull/4
