### ISSUE TITLE
Jenkins-Config - Pull Request Integration with Jenkins with developer-setup

### ISSUE THREAD

**Issue by smorin** [DemandCube/NeverwinterDP_Legacy#109]
I was using github and found an example of automatic CI testing of pull requests.  This is exactly what we need for all our repositories.  

1) Pick first project to integrate (https://github.com/DemandCube/developer-setup)
2) Create documentation on how to integrate projects pull requests into Jenkins
  a) How to setup Jenkins
  b) How to integrate Jenkins with a particular github repo "setup on github too"
  c) How to add tests to the Repo to be executed by Jenkins

Some documentation on how to set it up is here:
http://blog.kabisa.nl/2013/11/05/building-github-pull-requests-with-jenkins/

You can see the example here:
https://github.com/copitux/python-github3/pull/35

Here are a few related links
- http://stackoverflow.com/questions/15825770/github-pull-request-good-to-merge
- http://blog.travis-ci.com/announcing-pull-request-support/

![screen shot 2014-04-05 at 2 09 21 pm](https://cloud.githubusercontent.com/assets/124719/2623866/5618361a-bd0d-11e3-8321-acc1da64d09a.png)

**Comment by KingOfPoptart** [comment]
Also check out 

https://github.com/github/janky

**Comment by KingOfPoptart** [comment]
Checked in and reviewed
