### ISSUE TITLE
Get vagrant-flow working with the digitalocean provider

### ISSUE THREAD

**Issue by smorin** [DemandCube/NeverwinterDP_Legacy#111]
Add settings so that vagrant-flow will work with digital ocean for testing.

References
https://www.digitalocean.com/community/articles/how-to-use-digitalocean-as-your-provider-in-vagrant-on-an-ubuntu-12-10

**Comment by KingOfPoptart** [comment]
https://github.com/DemandCube/vagrant-flow/pull/11

**Comment by smorin** [comment]
@noitcudni If you can review this one it would be great

**Comment by KingOfPoptart** [comment]
Reviewed and merged
