### ISSUE TITLE
get vertx working in embedded mode for Sparkngin

### ISSUE THREAD

**Issue by smorin** [DemandCube/NeverwinterDP_Legacy#112]

**Comment by smorin** [comment]
vertx should log to kafka, it should be the the incoming URL, Server timestamp (unixtime) and post body (if post)

**Comment by smorin** [comment]
Do you think you'll get to work on this, during this week?

**Comment by ostadhashem** [comment]
Hi Steve,
Sorry for my late,
I'm working on it this week,
Thanks,
Sina

**Comment by smorin** [comment]
Note that:

You can get a mock producer here.

https://github.com/apache/kafka/blob/0.8.1/clients/src/main/java/org/apache/kafka/clients/producer/MockProducer.java

**Comment by smorin** [comment]
The body should be json

**Comment by smorin** [comment]
PS add into this ticket a sample Spec of what your planning to build for this.  Then we can discuss

**Comment by ostadhashem** [comment]
Thanks Steve, I check it tomorrow, and try to have a good design and plan

**Comment by smorin** [comment]
Perfect

On Wed, Apr 30, 2014 at 11:59 AM, Sina notifications@github.com wrote:

> Thanks Steve, I check it tomorrow, and try to have a good design and plan
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/DemandCube/NeverwinterDP/issues/112#issuecomment-41835657
> .

## 

Steve Morin | Hacker, Entrepreneur, Startup Advisor
twitter.com/SteveMorin | stevemorin.com
_Live the dream start a startup. Make the world ... a better place._

**Comment by KingOfPoptart** [comment]
@ostadhashem What's the status on this?
