### ISSUE TITLE
Document Demandcube vagrant cloudboxes on vagrant-flow README

### ISSUE THREAD

**Issue by smorin** [DemandCube/NeverwinterDP_Legacy#115]
These are related to #49 and #48, Believe @KingOfPoptart you did both already

**Comment by KingOfPoptart** [comment]
This is part of https://github.com/DemandCube/vagrant-flow/pull/11

Only Centos boxes are added though as no one has adde the Ubuntu images

**Comment by KingOfPoptart** [comment]
@louzar when you finish https://github.com/DemandCube/NeverwinterDP/issues/49  please update the readme and close this issue

**Comment by louzar** [comment]
ok

**Comment by smorin** [comment]
It's okay let's not focus on this for now.  Let's focus on just the issues for Demandspike like the execution wrapper and solving the statistics problem

**Comment by KingOfPoptart** [comment]
Just updated the README with Ubuntu image info.  Closing
