### ISSUE TITLE
Add support for 32-bit machines in developer-setup

### ISSUE THREAD

**Issue by mehikmat** [DemandCube/NeverwinterDP_Legacy#117]
Add support for 32-bit machines in developer-setup

**Comment by mehikmat** [comment]
@louzar I have added support Ubuntu
12.04 32-bit
12.10 32-bit
13.04-32-bit
and similarly for 64-bits.
Please get updates

**Comment by smorin** [comment]
This is great, please update the ticket as appropriate in Kanban

**Comment by smorin** [comment]
Also Hikmat if it's ready for review please announce it in the
neverwinterdp mailing list like it says in step 5 of
https://github.com/DemandCube/NeverwinterDP#workflow

**Comment by mehikmat** [comment]
Review request sent

**Comment by smorin** [comment]
Since this is in code review please put the link to the pull request in the ticket.
@louzar please verify

**Comment by louzar** [comment]
I verified on 2 virgin ubuntu 12, 32 and 64 where nothing is installed, I found the errors below, When you execute instalation in the second time, it works.
sudo: unable to resolve host ubuntu-12-x64-n2

[INFO]: Installing common developement tools************************************

./setup.sh: 73: [: Ubuntu: unexpected operator
./setup.sh: 91: [: Ubuntu: unexpected operator
./setup.sh: 123: [: 0: unexpected operator

./setup.sh: 134: [: 0: unexpected operator
INSTALLED: [ python ]
        2.7.3

./setup.sh: 156: [: 127: unexpected operator
INSTALLED: [ easy_install ]

./setup.sh: 180: [: 127: unexpected operator
INSTALLED: [ pip ]
        version_compare.py requires two arguments
Upgrading pip to 1.5
sudo: unable to resolve host ubuntu-12-x64-n2
sudo: pip: command not found
upgrading setuptools failed try manually

**Comment by mehikmat** [comment]
That's because ubuntu's shell by default points to dash and not to bash.So that is happening.
Either we have to make our shell point to bash before running script or need to put following line at the top of script since dash doesn't support some syntax of bash.
$ sudo ln -sf bash /bin/sh

I had put this line inside of bootstrap/os_meta_info.sh file's ubuntu section so it is working while running setup second time.

I will find solution for this.

**Comment by mehikmat** [comment]
https://github.com/mehikmat/developer-setup/blob/master/bootstrap/os_meta_info.sh#L54

**Comment by smorin** [comment]
Was there a pull request for this ticket?
