### ISSUE TITLE
Follow instructions to install Sparkngin-developer-setup

### ISSUE THREAD

**Issue by lazaruslarue** [DemandCube/NeverwinterDP_Legacy#123]
Encountering bug here in step 2, when using `./setup.sh`:
https://github.com/DemandCube/Sparkngin-developer-setup/issues/11

```
Bringing machine 'jenkinsdp' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* The box 'demandcube/centos-65_x86_64-VB-4.3.8' could not be found.


+ vagrant flow ansibleinventory
The provider for this Vagrant-managed machine is reporting that it
is not yet ready for SSH. Depending on your provider this can carry
different meanings. Make sure your machine is created and running and
try again. Additionally, check the output of `vagrant status` to verify
that the machine is in the state that you expect. If you continue to
get this error message, please view the documentation for the provider
you're using.
+ vagrant flow hostfile
+ vagrant flow playbook
ERROR: Unable to find an inventory file, specify one with -i ?
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again. 
```

**Comment by lazaruslarue** [comment]
```
[...p/Sparkngin-developer-setup]$ vagrant status                                                                   
Current machine states:

sparkngin1                not created (virtualbox)
sparkngin2                not created (virtualbox)
jenkinsdp                 not created (virtualbox)

This environment represents multiple VMs. The VMs are all listed
above with their current state. For more information about a specific
VM, run `vagrant status NAME`.
```

**Comment by lazaruslarue** [comment]
@stites says this fixes it: 

`vagrant box add demandcube/centos-65_x86_64-VB-4.3.8 https://vagrantcloud.com/demandcube/centos-65_x86_64-VB-4.3.8/version/1/provider/virtualbox.box`

**Comment by KingOfPoptart** [comment]
Are you running vagrant 1.5? You should double check that

**Comment by lazaruslarue** [comment]
@KingOfPoptart  good question. i just checked and it's version 1.4.3. that's strange because i just ran the developer-setup on a new directory this morning. 

I'll upgrade.

**Comment by KingOfPoptart** [comment]
https://github.com/DemandCube/developer-setup is out of date. Update vagrant locally and I'll file a
bug

**Comment by lazaruslarue** [comment]
Cool, thanks. I'm upgrading vagrant now. Will keep you posted. 

Relevant also, I got the boxes running but each attempt gave me a timeout message while the box was spinning up. When I ran it next, the previous box was 'already running'. Here's the output from last attempt.

```
Bringing machine 'sparkngin1' up with 'virtualbox' provider...
Bringing machine 'sparkngin2' up with 'virtualbox' provider...
Bringing machine 'jenkinsdp' up with 'virtualbox' provider...
[sparkngin1] VirtualBox VM is already running.
[sparkngin2] VirtualBox VM is already running.
[jenkinsdp] Importing base box 'demandcube/centos-65_x86_64-VB-4.3.8'...
[jenkinsdp] Matching MAC address for NAT networking...
[jenkinsdp] Setting the name of the VM...
[jenkinsdp] Clearing any previously set forwarded ports...
[jenkinsdp] Fixed port collision for 22 => 2222. Now on port 2201.
[jenkinsdp] Clearing any previously set network interfaces...
[jenkinsdp] Preparing network interfaces based on configuration...
[jenkinsdp] Forwarding ports...
[jenkinsdp] -- 22 => 2201 (adapter 1)
[jenkinsdp] Booting VM...
[jenkinsdp] Waiting for machine to boot. This may take a few minutes...
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period. This can
mean a number of things.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
```

**Comment by KingOfPoptart** [comment]
I get that too, vagrant tries a little too eagerly to connect, but it works eventually.

**Comment by lazaruslarue** [comment]
interestingly, when i went back and tried to `vagrant ssh jenkinsdp` i'm told the machine is unavail. I'll wait for this upgrade to finish downloading and try again from scratch

```
[... p/Sparkngin-developer-setup]$ vagrant ssh jenkinsdp                                            
VM must be created before running this command. Run `vagrant up` first.
```

**Comment by KingOfPoptart** [comment]
Also - I'm pretty sure you'll run into an issue when you run `vagrant flow playbook` because @smorin changed the script to sync with DeveloperPlaybooks instead of the other private playbooks repo.  DeveloperPlaybooks isn't up to date with what's in this setup anymore.  So... have fun.  

You can sync DemandcubePlaybooks instead and have flow-playbook.yml point to the new location to get the full set up for now until DeveloperPlaybooks is up to speed

**Comment by lazaruslarue** [comment]
>  I'm pretty sure you'll run into an issue  

lol... me too :)

**Comment by KingOfPoptart** [comment]
Issue https://github.com/DemandCube/NeverwinterDP/issues/127 and https://github.com/DemandCube/NeverwinterDP/issues/126 have been filed in response to this.

**Comment by lazaruslarue** [comment]
in addition to some problems getting the setup scripts working in developer-setup and sparkgin-developer-setup, this process was complicated by the ~/.vagrant.d/ folder that remained after installing vagrant with `brew`. After removing `/Applications/Varant`, `/usr/bin/vagrant` & `~/.vagrant.d/` i did not have any trouble getting this to work.

**Comment by smorin** [comment]
Vagrant with brew is definitely not the most suggested way.
