### ISSUE TITLE
improve assertionFunctions.py in QA-NeverwinterDP

### ISSUE THREAD

**Issue by anthonyms** [DemandCube/NeverwinterDP_Legacy#128]
Change checkIfFileExists to check existence of more than 1 file.

Sample config
config = {
        "name":"kafka-offset-monitor",
        "file": ["/usr/local/kafkaoffset/start","/usr/local/kafkaoffset/kafka-offset-monitor.jar"],
    }

parent is #72

**Comment by smorin** [comment]
Is there a pull request for this?

On Fri, Apr 11, 2014 at 1:34 AM, artfullyContrived <notifications@github.com

**Comment by anthonyms** [comment]
Yes. And it has been reviewed.

**Comment by smorin** [comment]
Please put the pull request in the issue please

**Comment by smorin** [comment]
Definitely add the pull request to the issue.

**Comment by KingOfPoptart** [comment]
This is https://github.com/DemandCube/QA-NeverwinterDP/pull/9
