### ISSUE TITLE
hadoop-hdfs-cleaner helps clean old files in hadoop, like log rotate would

### ISSUE THREAD

**Issue by smorin** [DemandCube/NeverwinterDP_Legacy#134]
Create a utility to cleanup hdfs files older than X minutes, in a specific directory and to recursively check sub directories for file.  

  It should use the hdfs commandline tools or the hdfs java api's for a utility that takes a property file with it's config to run with.  Can possibly add commandline arguments too 

Uses the repository: 
-   https://github.com/DemandCube/hadoop-hdfs-cleaner

Example of good documentation in README:
- https://github.com/DemandCube/filecrush
- https://github.com/DemandCube/vagrant-flow

```
# time should me in minutes
cleanup.default.time=60

# Override time for a individual directory
cleanup.IDENTIFIERNAME-1.time=60
cleanup.IDENTIFIERNAME-1.dir=hdfs://nn1.example.com/file1
cleanup.IDENTIFIERNAME-2.dir=s3n://nn1.example.com/file1
cleanup.IDENTIFIERNAME-3.dir=s3://nn1.example.com/file1
cleanup.IDENTIFIERNAME-4.dir=file:///file3
cleanup.IDENTIFIERNAME-5.dir=/user/hadoop/file4

```

Reference:
`hdfs fs -expunge`
`hdfs fs -rm -skipTrash`
`hadoop fs -Dfs.defaultFS=s3://myS3bucket -Dfs.trash.interval=0 -expunge`

HDFS file system example:
- https://github.com/nathanmarz/dfs-datastores/blob/develop/dfs-datastores/src/main/java/com/backtype/hadoop/Consolidator.java
- https://github.com/DemandCube/filecrush

HDFS Tutorial:
- https://developer.yahoo.com/hadoop/tutorial/module2.html#rebalancing

**Comment by jclavijo** [comment]
Ok, I started looking into a way to resolve this. The Trash and TrashPolicy classes in the Hadoop.fs api seem to allow specific configuration of the nodes through a Configuration file.  What does the re-balancing reference in the tutorial link provided's relation to the deletion of the files?
Is the plan for the data to be removed once re-balanced?
What is the reference to the consolidator?

**Comment by smorin** [comment]
"What does the re-balancing reference in the tutorial link provided's relation to the deletion of the files?" - It just details about the file system but isn't directly related to this ticket.
"Is the plan for the data to be removed once re-balanced?" - No this about just cleaning up old files not about rebalancing them.
"What is the reference to the consolidator?" - Is an example of using the HDFS Api's is all.

What progress have you been able to make? Do you have a V1 ready?

We are doing our builds with gradle
