### ISSUE TITLE
hadoop-datanode-rebalancer utility to balance blocks in hadoop

### ISSUE THREAD

**Issue by smorin** [DemandCube/NeverwinterDP_Legacy#135]
Utility to rebalance hdfs block on hadoop data nodes partitions on a single local data node.  

Example:

Location of blocks configure by:
- dfs.datanode.data.dir
- file://${hadoop.tmp.dir}/dfs/data
- Determines where on the local filesystem an DFS data node should store its blocks. If this is a comma-delimited list of directories, then data will be stored in all named directories, typically on different devices. Directories that do not exist are ignored.
- found in hdfs-default.xml or hdfs-site.xml

The utility should check that the datanode is stopped before running.

High level process is:
1. Stop the datanode
2. run hadoop-datanode-rebalancer
   - Read the hdfs-site.xml to pic hdfs partitions
   - Rebalance the HDFS partitions 
3. Start the datanode (it will reindex all the blocks you moved)
4. Done

Uses the repository: 
- https://github.com/DemandCube/hadoop-datanode-rebalancer

Example of good documentation in README:
- https://github.com/DemandCube/filecrush
- https://github.com/DemandCube/vagrant-flow

By default is should look for the default hdfs-site.xml but should allow for commandline argument to specify a hdfs-site.xml to use.

Example Usage:
- `hadoop-datanode-rebalancer/bin/rebalance [-f /path/to/hdfs-site.xml]`

This should be written in python or java.

References:
- [ FAQ abouthow do you balance the blocks on the disk WHAT THIS IS DOING](http://wiki.apache.org/hadoop/FAQ#On_an_individual_data_node.2C_how_do_you_balance_the_blocks_on_the_disk.3F)
- [Sysadmin discussing block rebalancing](http://hadoopadmin.blogspot.com/2012/03/balancing-data-equally-among-disks-on.html)
- [HDFS tutorial](https://developer.yahoo.com/hadoop/tutorial/module2.html#rebalancing)

**Comment by noitcudni** [comment]
I have already started on this, but I don't seem to have the right permission to git push.

**Comment by smorin** [comment]
Ah sorry il fix that

**Comment by smorin** [comment]
You should have permission now

On Sun, Apr 13, 2014 at 1:29 PM, Steve Morin steve.morin@gmail.com wrote:

> Ah sorry il fix that
> 
> On Apr 13, 2014, at 11:24, Lih Chen notifications@github.com wrote:
> 
> I have already started on this, but I don't seem to have the right
> permission to git push.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/DemandCube/NeverwinterDP/issues/135#issuecomment-40315114
> .

## 

Steve Morin | Hacker, Entrepreneur, Startup Advisor
twitter.com/SteveMorin | stevemorin.com
_Live the dream start a startup. Make the world ... a better place._

**Comment by KingOfPoptart** [comment]
@noitcudni What's the status of this issue?

**Comment by noitcudni** [comment]
done

**Comment by KingOfPoptart** [comment]
@noitcudni If issues are done, please feel free to close them.
