### ISSUE TITLE
finish running sparkngin developer setup

### ISSUE THREAD

**Issue by pieteradejong** [DemandCube/NeverwinterDP_Legacy#139]

**Comment by pieteradejong** [comment]
Current machine states:

sparkngin1                running (virtualbox)
sparkngin2                running (virtualbox)
jenkinsdp                 poweroff (virtualbox)

> vagrant up:
> Bringing machine 'sparkngin1' up with 'virtualbox' provider...
> Bringing machine 'sparkngin2' up with 'virtualbox' provider...
> Bringing machine 'jenkinsdp' up with 'virtualbox' provider...
> ==> sparkngin1: Checking if box 'demandcube/centos-65_x86_64-VB-4.3.8' is up to date...
> ==> sparkngin1: VirtualBox VM is already running.
> ==> sparkngin2: Checking if box 'demandcube/centos-65_x86_64-VB-4.3.8' is up to date...
> ==> sparkngin2: VirtualBox VM is already running.
> ==> jenkinsdp: Checking if box 'demandcube/centos-65_x86_64-VB-4.3.8' is up to date...
> A VirtualBox machine with the name 'jenkinsdp' already exists.
> Please use another name or delete the machine with the existing
> name, and try again.

**Comment by KingOfPoptart** [comment]
Outdated, closing.
