### ISSUE TITLE
Develop Nginx Json Plugin

### ISSUE THREAD

**Issue by smorin** [DemandCube/NeverwinterDP_Legacy#14]
Create a nginx module that creates a nginx variable that contains a json map object that is from other text that can include nginx variables.
Does this make sense Hikmat?

Spec:

sparkngin_json_variable: variable-name ;
sparkngin_json_put: variable-name keyname "keyvalue"

e.g.  

location /www/ {
 sparkngin_json_variable: payload_json;
 sparkngin_json_put: payload_json  status "$status"
 sparkngin_json_put: payload_json  time    "$msec"
 sparkngin_json_put: payload_json  version "1.0"
 sparkngin_json_put: payload_json  appid "pid:$pid"
 log_format: "$payload_json"
}

**Comment by smorin** [comment]
sparkngin_json_variable: variablename
  This is a directive that sets the name of the variable that would be created by the JSON module.  This creates a variable that contains a JSON map object.

sparkngin_json_put: variablename keyname "keyvalue"
  This is the name of the directive that adds keys and values to the JSON map created with `sparkngin_json_variable`

```
variablename: this is a reference to the variable name created by sparkngin_json_variable.
keyname: this is the name of the key to be created in the json object.
"keyvalue": This is a string that quoted, it can contain literal values and also nginx variables that are interpolated.
```

All of these directives get put in the nginx config.

Please explain spec in more detail

**Comment by KingOfPoptart** [comment]
@mehikmat What's the status on this?  Who do you need to code review this?
