### ISSUE TITLE
get kafka running on Tomcat or Jetty server

### ISSUE THREAD

**Issue by pieteradejong** [DemandCube/NeverwinterDP_Legacy#140]

**Comment by smorin** [comment]
Kafka is a  standalone service and won't run on either.

**Comment by stites** [comment]
I think Pieter means "get a jetty webserver interfacing with kafka." This is already done with SparkJava. We need to start building out the API next.

**Comment by KingOfPoptart** [comment]
@pieteradejong @stites What's the status on this?  Can we close this issue?
