### ISSUE TITLE
CR: fix Sparkngin setup script to work with non-empty ansible folder

### ISSUE THREAD

**Issue by lazaruslarue** [DemandCube/NeverwinterDP_Legacy#143]
https://github.com/lazaruslarue/Sparkngin-developer-setup.git
@noitcudni

**Comment by smorin** [comment]
@lazaruslarue  What do you mean by this?  I don't understand the ticket.

**Comment by lazaruslarue** [comment]
if the ansible folder contains any documents (which it does upon cloning) then the instruction changed by the PR will fail in OSX.

**Comment by lazaruslarue** [comment]
This PR has since been merged, solves the in-question issue: https://github.com/DemandCube/Sparkngin-developer-setup/commit/cb8c300671e65bde8b9ea66dfa0e092adec76bd9
