### ISSUE TITLE
Move jenkinsdp virtual box out of Sparkngin-developer-setup

### ISSUE THREAD

**Issue by KingOfPoptart** [DemandCube/NeverwinterDP_Legacy#144]
Currently, https://github.com/DemandCube/Sparkngin-developer-setup/blob/master/setup.sh sets up 3 machines.  

We need to pull the functionality of creating the jenkindp machine into a separate setup

**Comment by KingOfPoptart** [comment]
Also will need to update https://github.com/DemandCube/Sparkngin-developer-setup/blob/master/README.md

**Comment by smorin** [comment]
Rich was this done?

**Comment by KingOfPoptart** [comment]
yes
