### ISSUE TITLE
Latest update to Sparkngin-developer-setup breaks setup

### ISSUE THREAD

**Issue by KingOfPoptart** [DemandCube/NeverwinterDP_Legacy#145]
https://github.com/DemandCube/Sparkngin-developer-setup/commit/cb8c300671e65bde8b9ea66dfa0e092adec76bd9  needs to be reverted or at least updated.

If the "Sparkngin-developer-setup/DeveloperPlaybooks/library" folder already exists then it works, but this is not the usual use case.  The normal use case is that you're dealing with a clean slate

This breaks functionality for a clean set up.  Either the script should be reverted and this use case of a dirty environment should be ignored, or the setup script should be able to intelligently handle both cases.

**Comment by smorin** [comment]
@lazaruslarue can you please verify this ticket?

**Comment by lazaruslarue** [comment]
@smorin @KingOfPoptart i'll dig into it on my new Azure instance :) Stay tuned for details.

**Comment by smorin** [comment]
Thanks

On Wed, Apr 30, 2014 at 11:19 AM, lazaruslarue notifications@github.comwrote:

> @smorin https://github.com/smorin @KingOfPoptarthttps://github.com/KingOfPoptarti'll dig into it on my new Azure instance :) Stay tuned for details.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/DemandCube/NeverwinterDP/issues/145#issuecomment-41830674
> .

## 

Steve Morin | Hacker, Entrepreneur, Startup Advisor
twitter.com/SteveMorin | stevemorin.com
_Live the dream start a startup. Make the world ... a better place._

**Comment by lazaruslarue** [comment]
@smorin i think @KingOfPoptart is right. this should be reverted. i'll submit another PR to undo it.
