### ISSUE TITLE
Connect Hadoop/Kafka to the SparkJava server in testing bed

### ISSUE THREAD

**Issue by stites** [DemandCube/NeverwinterDP_Legacy#150]
From the Apache Kafka book from packetpub, I'd like to solidify the last part of learning by connecting the spark server to the hadoop/kafka setup.

**Comment by stites** [comment]
for starters I'm only working with one broker/producer/topic/consumer

**Comment by stites** [comment]
#### Blocked on two levels:
- The default sparkngin2 which runs kafka on it throws an error with the version_check module from ansible-flow. This is referenced in #148
- I've moved forward with a side-setup of a base centos-vagrantbox. The blocker here is that kafka is starting to hang when instantiating producers.

#### Proposed methods for unblocking:

Fix #148 seems to be the highest value. I would like to go over both issues I am having - both with ansible-flow and the kafka bug. @smorin - is there someone in particular I should ping on this?

**Comment by smorin** [comment]
Is 148 still relevant or should it be closed?

**Comment by stites** [comment]
closing it now

**Comment by stites** [comment]
finished and am pushing this into the example server in kafkasphere/dev

**Comment by smorin** [comment]
Just send the pull request to master
-Steve

On Mon, May 5, 2014 at 4:56 PM, Sam Stites notifications@github.com wrote:

> finished and am pushing this into the example server in kafkasphere/dev
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/DemandCube/NeverwinterDP/issues/150#issuecomment-42254752
> .

## 

Steve Morin | Hacker, Entrepreneur, Startup Advisor
twitter.com/SteveMorin | stevemorin.com
_Live the dream start a startup. Make the world ... a better place._
