### ISSUE TITLE
Prepare public open source yarn example project with documentation

### ISSUE THREAD

**Issue by smorin** [DemandCube/NeverwinterDP_Legacy#153]

**Comment by noitcudni** [comment]
https://github.com/DemandCube/yarn-app

**Comment by noitcudni** [comment]
Trying to see if this issue shows up if I were to re-open it

**Comment by smorin** [comment]
So I can close this Lih?

**Comment by smorin** [comment]
Did the issue show up when you reopened it?

On Wed, Apr 16, 2014 at 5:53 AM, Lih Chen notifications@github.com wrote:

> Trying to see if this issue shows up if I were to re-open it
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/DemandCube/NeverwinterDP/issues/153#issuecomment-40565556
> .

## 

Steve Morin | Hacker, Entrepreneur, Startup Advisor
twitter.com/SteveMorin | stevemorin.com
_Live the dream start a startup. Make the world ... a better place._

**Comment by noitcudni** [comment]
yes, can close it.
