### ISSUE TITLE
Review code review solutions - must first party support for github - huboard

### ISSUE THREAD

**Issue by smorin** [DemandCube/NeverwinterDP_Legacy#154]
The main need is a place to track, what issues need code reviews and which are waiting for changes, which are accepted or rejected

TODO:
- Research tool options
- Test using the tools
- List all tools reviewed 
  - Pros
  - Cons
  - Recommendation and why

The tool needs to:
- Tool lets us see which github pull request need to be reviewed (waiting for a reviewer)
- Tool lets us see if we are assigned a code review
- Tool lets us see which  code reviews are waiting for answers or changes to the code be completed
- Tool let us see which code has been accepted or rejected

Some tools to review
- https://codifferous.com/
- http://getbarkeep.org/
- Sonar
- http://www.reviewboard.org/
- https://www.atlassian.com/software/crucible
- http://phabricator.org/
- http://groogle.sourceforge.net/index.php

**Comment by smorin** [comment]
There is a reference to Huboard ticket

Issue on Huboard
https://github.com/rauhryan/huboard/issues/323

**Comment by smorin** [comment]
States that would be good to have are things like:
- None (No review state) = "There is no review state at all - basically pre-request"
- Review request (Any or Specific User) = "A code review is needed, can be for anyone to review or a specific person(s)"
- Review accepted = "A user accepts a 'Review request'"
- In review = "Person is actively reviewing this code"
- Awaiting changes = "A person was reviewing and requested changes or asked questions and is waiting for a response"
- Rejected = "This issue or code won't be accepted, should include a comment as why in the issue too."
- Accepted = "This issue is accepted by the reviewer"

**Comment by KingOfPoptart** [comment]
Here is a mock up of what the columns and tabs will look like
![huboardmockup](https://cloud.githubusercontent.com/assets/5826660/2714874/1ffef51a-c4ff-11e3-91ff-feffa9ee429b.png)

Here is a mock up for what will pop up when hitting the "Create New Issue" button will pop up
![newissuemockup](https://cloud.githubusercontent.com/assets/5826660/2714877/2a03b3f2-c4ff-11e3-91c9-5e1138871869.png)

This mock up is for when you click open an existing issue
![issuemockup](https://cloud.githubusercontent.com/assets/5826660/2715100/9838b822-c504-11e3-8b3b-cce6c2b8ce76.png)

**Comment by smorin** [comment]
Awesome!

**Comment by KingOfPoptart** [comment]
Balsamiq file (v1.0) here - https://groups.google.com/group/neverwinterdp/attach/9b746ad78d56ffac/huboard_reviewer_mockup_1.0.zip?part=4&authuser=0

**Comment by ostadhashem** [comment]
Here is a comparison between these tools:
http://lifetechnology-narin.blogspot.com/2012/09/list-of-code-review-tools-comparison.html

**Comment by smorin** [comment]
create - huboard
1) Publish Spec on Data Model
2) Reviews UI features

**Comment by KingOfPoptart** [comment]
@smorin Do we need to keep this issue open?

**Comment by KingOfPoptart** [comment]
Moving to backlog for now.  Design is done, requires implementation
