### ISSUE TITLE
Weekly Project Summary Report Generator: Planning

### ISSUE THREAD

**Issue by anthonyms** [DemandCube/NeverwinterDP_Legacy#157]
Reading up on sparkjava, jcabi-github, gradle.
Then organize thought process to best implement it.

parent is #108

**Comment by anthonyms** [comment]
@smorin  and Team,

I have come up with the following design decisions and need your views on them.
The mockup shows the ui for the web interface.

The UI is to designed to allow a user view in a sortable table issues opened and closed within a date range. This could be for a single repo or all of a users repos.
1. On providing a user/organization (e.g. DemandCube) the Repos dropdown is populated with the users public repositories.
2. Minimum start date = repo creation date
3. Maximum end date = current date.
4. The table will show the issue number, description, date issue created,  assignee, date closed.
5. All columns are sortable.
6. No need to save anything locally as we can get them from github.
7. Default to anonymous login. (GitHub allows it but limits number of requests.)
8. The weekly report will be a cron job sending out an excel file to repository users. The job will be fired off on Mondays 0800 UTC.

Advice? Comments?

![mockup](https://cloud.githubusercontent.com/assets/445103/2826239/289bb5e4-cf6a-11e3-9bb1-51584bd65e62.png)

**Comment by KingOfPoptart** [comment]
Instead of a drop down for Repository, can it be checkboxes instead, so
that we can select multiple repo's at once?

**Comment by anthonyms** [comment]
Noted.

**Comment by anthonyms** [comment]
Team,

Attached is the proposed Sample Weekly report.
Comments welcome.

https://dl.dropboxusercontent.com/u/18673274/21%2004%202014.xlsx

**Comment by louzar** [comment]
I suggest adding drop down for the issue status

**Comment by smorin** [comment]
The Dropdown should have the option to select "All"

It should let you filter by issues, pull request but default to "Both"

Additionally the drop down should have columns for:
Repository, Type (Issue/Pull Request), Milestone

Does this make sense?  Do you have other questions?

**Comment by smorin** [comment]
Looked at the spreadsheet and want to have the fields added that I
mentioned in the comments

On Tue, Apr 29, 2014 at 3:15 PM, artfullyContrived <notifications@github.com

> wrote:
> 
> Team,
> 
> Attached is the proposed Sample Weekly report.
> Comments welcome.
> 
> https://dl.dropboxusercontent.com/u/18673274/21%2004%202014.xlsx
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/DemandCube/NeverwinterDP/issues/157#issuecomment-41689324
> .

## 

Steve Morin | Hacker, Entrepreneur, Startup Advisor
twitter.com/SteveMorin | stevemorin.com
_Live the dream start a startup. Make the world ... a better place._

**Comment by anthonyms** [comment]
In addition to all other  comments:
1. The repository drop-down should allow multiple selection
2. The repository drop-down should have an 'All' option
3. The issues/pull request button group be changed to check boxes to allow
   for the 'Both' option
4. An additional "Status" drop down.

The comments in #108 will be included in the excel sheet as summaries since
we already have the needed data.
Am still looking to see how the Github api handles pull requests.

**Comment by smorin** [comment]
Sounds good

On Wed, Apr 30, 2014 at 2:13 AM, artfullyContrived <notifications@github.com

> wrote:
> 
> In addition to all other comments:
> 1. The repository drop-down should allow multiple selection
> 2. The repository drop-down should have an 'All' option
> 3. The issues/pull request button group be changed to check boxes to allow
>    for the 'Both' option
> 4. An additional "Status" drop down.
> 
> The comments in #108 will be included in the excel sheet as summaries
> since
> we already have the needed data.
> Am still looking to see how the Github api handles pull requests.
> 
> On Wed, Apr 30, 2014 at 10:28 AM, Steve Morin notifications@github.comwrote:
> 
> > The Dropdown should have the option to select "All"
> > 
> > It should let you filter by issues, pull request but default to "Both"
> > 
> > Additionally the drop down should have columns for:
> > Repository, Type (Issue/Pull Request), Milestone
> > 
> > Does this make sense? Do you have other questions?
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/DemandCube/NeverwinterDP/issues/157#issuecomment-41767998>
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/DemandCube/NeverwinterDP/issues/157#issuecomment-41775910
> .

## 

Steve Morin | Hacker, Entrepreneur, Startup Advisor
twitter.com/SteveMorin | stevemorin.com
_Live the dream start a startup. Make the world ... a better place._

**Comment by anthonyms** [comment]
Team,

Please provide feedback on the attached proposed weekly report.

https://www.dropbox.com/s/iouw6mttcgoeqvv/31%2003%202014.xlsx

**Comment by smorin** [comment]
This looks great!

On Tue, May 6, 2014 at 7:58 AM, artfullyContrived
notifications@github.comwrote:

> Team,
> 
> Please provide feedback on the attached proposed weekly report.
> 
> https://www.dropbox.com/s/iouw6mttcgoeqvv/31%2003%202014.xlsx
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/DemandCube/NeverwinterDP/issues/157#issuecomment-42313308
> .

## 

Steve Morin | Hacker, Entrepreneur, Startup Advisor
twitter.com/SteveMorin | stevemorin.com
_Live the dream start a startup. Make the world ... a better place._

**Comment by louzar** [comment]
look good

2014-05-06 15:58 GMT+01:00 artfullyContrived notifications@github.com:

**Comment by anthonyms** [comment]
@smorin Should the report be mailed to the group address (neverwinterdp[at]googlegroups) or to the collaborators individual addresses?

**Comment by anthonyms** [comment]
From the weekly meeting, report to be sent out to demandcube collaborators addresses.
