### ISSUE TITLE
git error: Unable to find remote helper for 'https' 

### ISSUE THREAD

**Issue by mehikmat** [DemandCube/NeverwinterDP_Legacy#159]
Today I found an error with git 
To replicate:
$ git clone https://github.com/DemandCube/developer-setup.git
$ cd developer-setup
$ ./setup.sh
After this, everything installs successfully without any error but after installation
when executing command
$ git clone https://any_git_repo_url/repo.git
Following error occurs
Unable to find remote helper for 'https'

**Comment by mehikmat** [comment]
Which was happening due to tow git dependencies:
libcurl4-gnutls-dev, libexpat1-dev in case of ubuntu and 
curl-devel expat-devel in case of CentOS 

I have added these git dependencies  in git installation section of  https://github.com/DemandCube/developer-setup.git.
Now issue fixed and git is working

**Comment by smorin** [comment]
Thanks for adding this!

**Comment by smorin** [comment]
Was there a pull request for this ticket?

**Comment by mehikmat** [comment]
Yes this was https://github.com/DemandCube/developer-setup/pull/7 which you had merged.

**Comment by smorin** [comment]
Please place the pull request in all issues so we can close them

On Wed, Apr 30, 2014 at 2:29 AM, Hikmat Dhamee notifications@github.comwrote:

> Yes this was DemandCube/developer-setup#7https://github.com/DemandCube/developer-setup/pull/7which you had merged.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/DemandCube/NeverwinterDP/issues/159#issuecomment-41777293
> .

## 

Steve Morin | Hacker, Entrepreneur, Startup Advisor
twitter.com/SteveMorin | stevemorin.com
_Live the dream start a startup. Make the world ... a better place._
