### ISSUE TITLE
Upgrade kafka role to default to kafka-0.8.1

### ISSUE THREAD

**Issue by stites** [DemandCube/NeverwinterDP_Legacy#163]

**Comment by stites** [comment]
Did this ever get done? @noitcudni I'll spin up a new environment on my work computer and see if this is still persisting.

**Comment by noitcudni** [comment]
There's an even newer version of kafka out now. 0.8.1.1. So no, this is not done.

**Comment by stites** [comment]
Okay - setting up the environment from scratch, I'll work on this one at the same time.

**Comment by KingOfPoptart** [comment]
@stites are you still working on this?
