### ISSUE TITLE
Find or build tool to generate a change log for repos.

### ISSUE THREAD

**Issue by smorin** [DemandCube/NeverwinterDP_Legacy#164]
Here is a good example:
http://jasonbradley.me/creating-a-changelog-from-github/
http://www.lornajane.net/posts/2014/github-powered-changelog-scripts

**Comment by mehikmat** [comment]
Finally I have come to a point that there is a useful tool in github for generating  changelogs and  
 many more reports.

I think using this tool is fine for our requirements.

Please have look at below link  for more info:
[Git-Extras Tool to generate changelog and many more reports](https://github.com/visionmedia/git-extras)

**Comment by smorin** [comment]
Have you tested it?Can you show an example of using it and the output?The point of evaluating tools is to show them in useSent from AcompliOn Sun, May 11, 2014 at 11:52 AM -0700, "Hikmat Dhamee" notifications@github.com wrote:

Finally I have come to a point that there is a useful tool in github generating  changelogs and
 many more reports.

I think using this tool is fine for our requirements.

Please have look at below link  for more info:Git-Extras Tool to generate changelog and many more reports

**Comment by mehikmat** [comment]
Using _git-extras_ to generate changelog

## To install git-extras

`$ cd /tmp && git clone https://github.com/visionmedia/git-extras.git && cd git-extras && sudo make install`

## Generate changelog (git changelog)

Populate a file whose name matches _changelog or history_ (if there is no any file named CHANGELOG or HISTORY then it creates History.md by default) with commits since the previous tag. (If there are no tags, populates commits since the project began.)
Opens the changelog in $EDITOR if environment variable $EDITOR is set.

```
For Example:
$ cd NeverwinterDP
$ git changelog
$ cat History.md

n.n.n / 2014-05-12
==================
 * Merge pull request #194 from tuan08/feature/prototype
 * clean empty line
 * Update README.md
 * Move the message to its package
 * Move the message to its package
 * refractor the Message, move the Message to its own package and ReportMessageWriter and unit test
 * refractor the Message, move the Message to its own package
 * Move the Message api to the message package and reorganize the code
 * clean try catch exception
 * temporarily move the message api to common and define the message api
 * add statistic util code
 * Update Readme.md
 * create MessageLog and MessageInstruction
 * revert Readme.md commit
 * update Readme.md
 * update README.md
 * update README.md
 * update README.md
 * Refractor the client code api to use event/model to work better with Vertx, add Vertx http clien
 * clean try/catch exception
 * throw RuntimeException instead of IOException
 * turn on auto commit , we should manage the commit ourself later
 * add onErrorMessage api
 * add InMemoryDB and MessageWriter unit test
 * fix reversed commit call
 * update the subproject configuration and dependencies
 * add MessageWriter api and implement a mock in memory db
 * add some code for demandspike framework
 * add sample vertx code and implement vertx message rest service
 * add sample vertx code and implement vertx message rest service
 * allow serialize List to byte[]
 * clean and reorganize queuengin code
 * add dummy json message consumer
 * add vertx server
 * add vertx server
 * rename the packahe queue to queuengin
 * rename the packahe queue to queuengin
 * update junit version
 * add vertx sample code
 * update Readme.md
 * update Readme.md
 * clean build directory
 * update Readme.md
 * update Readme.md
 * create test-framework project and reorganize test code
 * clean build directory
 * first prototype check in
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * adding in .gitignore and new architecture diagrams
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Create LICENSE
 * Update NEVERWINTERDP
 * Update README.md
 * Create NEVERWINTERDP
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * add todo markup
 * Create todo
 * adding a proper wiki section
 * Merge branch 'master' of github.com:DemandCube/NeverwinterDP
 * adding a proper wiki section
 * Update README.md
 * Update MAC_DEP_README
 * Update MAC_DEP_README
 * Update MAC_DEP_README
 * Update MAC_DEP_README
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Build tool instructions
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Merge branch 'master' of github.com:DemandCube/NeverwinterDP
 * adding high level diagram
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Update README.md
 * Initial commit
```

List commits:

```
$ git changelog --list
 * Merge pull request #194 from tuan08/feature/prototype
 * clean empty line
 * Update README.md
 * Move the message to its package
 * Move the message to its package
 * refractor the Message, move the Message to its own package and ReportMessageWriter and unit test
 * refractor the Message, move the Message to its own package
 * Move the Message api to the message package and reorganize the code
 * clean try catch exception
 * temporarily move the message api to common and define the message api
 * add statistic util code
 * Update Readme.md
 * create MessageLog and MessageInstruction
 * revert Readme.md commit
 * update Readme.md
 * update README.md
 * update README.md
 * update README.md
 * Refractor the client code api to use event/model to work better with Vertx, add Vertx http clien
 * clean try/catch exception
 * throw RuntimeException instead of IOException
 * turn on auto commit , we should manage the commit ourself later
 * add onErrorMessage api
 * add InMemoryDB and MessageWriter unit test
 * fix reversed commit call
 * update the subproject configuration and dependencies
 * add MessageWriter api and implement a mock in memory db
 * add some code for demandspike framework
 * add sample vertx code and implement vertx message rest service
 * add sample vertx code and implement vertx message rest service
 * allow serialize List to byte[]
 * clean and reorganize queuengin code
 * add dummy json message consumer
 * add vertx server
 * add vertx server
 * rename the packahe queue to queuengin
 * rename the packahe queue to queuengin
 * update junit version
 * add vertx sample code
 .
 .
 .
 .
```

## View Project Summary

```
$ git summary
project  : NeverwinterDP
 repo age : 8 months
 active   : 49 days
 commits  : 169
 files    : 86
 authors  : 
   123  Steve Morin             72.8%
    45  tuan08                  26.6%
     1  Tuan Nguyen             0.6%
```

## Generate changelog since specific tag

```
$ git changelog --tags tag_name
```

##NOTE

if there is no any tags this tool throws error like 
.......
......
fatal: No names found, cannot describe anything.

But this doesn't cause any problem with changelog generation.

**Comment by smorin** [comment]
Okay thanks
-Steve

On Mon, May 12, 2014 at 1:18 AM, Hikmat Dhamee notifications@github.comwrote:

> Using _git-extras_ to generate changelog To install git-extras
> 
> $ cd /tmp && git clone https://github.com/visionmedia/git-extras.git &&
> cd git-extras && sudo make install
> Generate changelog (git changelog)
> 
> Populate a file whose name matches _changelog or history_ (if there is no
> any file named CHANGELOG or HISTORY then it creates History.md by default)
> with commits since the previous tag. (If there are no tags, populates
> commits since the project began.)
> Opens the changelog in $EDITOR if environment variable $EDITOR is set.
> 
> For Example:
> $ cd NeverwinterDP
> $ git changelog
> $ cat History.md
> 
> # n.n.n / 2014-05-12
> - Merge pull request #194 from tuan08/feature/prototype
> - clean empty line
> - Update README.md
> - Move the message to its package
> - Move the message to its package
> - refractor the Message, move the Message to its own package and ReportMessageWriter and unit test
> - refractor the Message, move the Message to its own package
> - Move the Message api to the message package and reorganize the code
> - clean try catch exception
> - temporarily move the message api to common and define the message api
> - add statistic util code
> - Update Readme.md
> - create MessageLog and MessageInstruction
> - revert Readme.md commit
> - update Readme.md
> - update README.md
> - update README.md
> - update README.md
> - Refractor the client code api to use event/model to work better with Vertx, add Vertx http clien
> - clean try/catch exception
> - throw RuntimeException instead of IOException
> - turn on auto commit , we should manage the commit ourself later
> - add onErrorMessage api
> - add InMemoryDB and MessageWriter unit test
> - fix reversed commit call
> - update the subproject configuration and dependencies
> - add MessageWriter api and implement a mock in memory db
> - add some code for demandspike framework
> - add sample vertx code and implement vertx message rest service
> - add sample vertx code and implement vertx message rest service
> - allow serialize List to byte[]
> - clean and reorganize queuengin code
> - add dummy json message consumer
> - add vertx server
> - add vertx server
> - rename the packahe queue to queuengin
> - rename the packahe queue to queuengin
> - update junit version
> - add vertx sample code
> - update Readme.md
> - update Readme.md
> - clean build directory
> - update Readme.md
> - update Readme.md
> - create test-framework project and reorganize test code
> - clean build directory
> - first prototype check in
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - adding in .gitignore and new architecture diagrams
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Create LICENSE
> - Update NEVERWINTERDP
> - Update README.md
> - Create NEVERWINTERDP
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - add todo markup
> - Create todo
> - adding a proper wiki section
> - Merge branch 'master' of github.com:DemandCube/NeverwinterDP
> - adding a proper wiki section
> - Update README.md
> - Update MAC_DEP_README
> - Update MAC_DEP_README
> - Update MAC_DEP_README
> - Update MAC_DEP_README
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Build tool instructions
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Merge branch 'master' of github.com:DemandCube/NeverwinterDP
> - adding high level diagram
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Update README.md
> - Initial commit
> 
> List commits:
> 
> $ git changelog --list
> - Merge pull request #194 from tuan08/feature/prototype
> - clean empty line
> - Update README.md
> - Move the message to its package
> - Move the message to its package
> - refractor the Message, move the Message to its own package and ReportMessageWriter and unit test
> - refractor the Message, move the Message to its own package
> - Move the Message api to the message package and reorganize the code
> - clean try catch exception
> - temporarily move the message api to common and define the message api
> - add statistic util code
> - Update Readme.md
> - create MessageLog and MessageInstruction
> - revert Readme.md commit
> - update Readme.md
> - update README.md
> - update README.md
> - update README.md
> - Refractor the client code api to use event/model to work better with Vertx, add Vertx http clien
> - clean try/catch exception
> - throw RuntimeException instead of IOException
> - turn on auto commit , we should manage the commit ourself later
> - add onErrorMessage api
> - add InMemoryDB and MessageWriter unit test
> - fix reversed commit call
> - update the subproject configuration and dependencies
> - add MessageWriter api and implement a mock in memory db
> - add some code for demandspike framework
> - add sample vertx code and implement vertx message rest service
> - add sample vertx code and implement vertx message rest service
> - allow serialize List to byte[]
> - clean and reorganize queuengin code
> - add dummy json message consumer
> - add vertx server
> - add vertx server
> - rename the packahe queue to queuengin
> - rename the packahe queue to queuengin
> - update junit version
> - add vertx sample code
>   .
>   .
>   .
>   .
> 
> View Project Summary
> 
> $ git summary
> project  : NeverwinterDP
>  repo age : 8 months
>  active   : 49 days
>  commits  : 169
>  files    : 86
>  authors  :
>    123  Steve Morin             72.8%
>     45  tuan08                  26.6%
>      1  Tuan Nguyen             0.6%
> 
> ##NOTE##:
> 
> if there is no any tags this tool throws error like
> 
> .......
> ......
> fatal: No names found, cannot describe anything.
> 
> But this doesn't cause any problem with changelog generation.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/DemandCube/NeverwinterDP/issues/164#issuecomment-42796788
> .

## 

Steve Morin | Hacker, Entrepreneur, Startup Advisor
twitter.com/SteveMorin | stevemorin.com
_Live the dream start a startup. Make the world ... a better place._

**Comment by KingOfPoptart** [comment]
@mehikmat what's the status on this?
