### ISSUE TITLE
Install code quality checks sonar and integrate with Jenkins

### ISSUE THREAD

**Issue by smorin** [DemandCube/NeverwinterDP_Legacy#165]
http://cvuorinen.net/2013/07/installing-sonarqube-with-jenkins-integration-for-a-php-project/
http://en.wikipedia.org/wiki/SonarQube

**Comment by mehikmat** [comment]
To setup code quality checks tool, sonar, we need to
- install sonarqube server
- install sonar-runner
- install sonar jenkins plugin
- configure jenkins for sonar

So do I need to create a bash script to do all this or need to add some roles to [jenkins-developer-setup repo](https://github.com/DemandCube/jenkins-developer-setup)

**Comment by KingOfPoptart** [comment]
What's the status of this @mehikmat ?
