### ISSUE TITLE
important metrics for kafka sphere to track

### ISSUE THREAD

**Issue by smorin** [DemandCube/NeverwinterDP_Legacy#170]
BytesInCount
BytesOutCount
BytesInPerSecond
BytesOutPerSecond
FailedProduceRequestsCount
FailedProduceRequestsPerSecond
FailedFetchRequestsCount
FailedFetchRequestsPerSecond
MessageInCount
MessageInPerSecond

**Comment by anthonyms** [comment]
Related #107

**Comment by smorin** [comment]
Yes definitely related to #107 , figure to tool from #107 will be used to find these metrics.
