### ISSUE TITLE
github-flow - Create initial version of github-flow as a pip install, should list all open Pull Request

### ISSUE THREAD

**Issue by smorin** [DemandCube/NeverwinterDP_Legacy#175]
# Background on setup tools:
- https://pythonhosted.org/setuptools/
- https://pythonhosted.org/setuptools/setuptools.html
- https://pythonhosted.org/setuptools/easy_install.html
- https://pythonhosted.org/setuptools/formats.html
- https://pythonhosted.org/setuptools/pkg_resources.html
# compare with existing examples
- https://github.com/ansible/ansible/blob/devel/setup.py
- https://github.com/ansible/ansible/blob/devel/bin/ansible
# nosetests
- https://nose.readthedocs.org/en/latest/
# Sphinx Documentation
- http://sphinx-doc.org/
- http://stackoverflow.com/questions/4547849/good-examples-of-python-docstrings-for-sphinx
- http://raxcloud.blogspot.com/2013/02/documenting-python-code-using-sphinx.html

**Comment by KingOfPoptart** [comment]
@mehikmat What's the status on this?
