### ISSUE TITLE
jenkins-flow - create jenkins plugin that takes a travis like config.

### ISSUE THREAD

**Issue by smorin** [DemandCube/NeverwinterDP_Legacy#176]
Repo:
- https://github.com/DemandCube/jenkins-flow

The config should allow you to set 3 aspects:
- Machine Provisioning (OS and System Requirements)
- Dependencies / Setup
- List of commands - Build/Tests

Under machine provisioning is deploying with digital ocean
- https://wiki.jenkins-ci.org/display/JENKINS/Plugin+tutorial

Machine Provisioning implementation could be a fixed machine for each OS and then a new docker image for each machine.

Dependencies implementation could be the running of ansible on that docker image.  Then copying this repo to install on this machine.

List of commands - Build/Tests  implementation could be done by running specific commands in that docker machine.

References:
- http://www.nuxeo.com/blog/development/2014/02/docker-jenkins-cloud-provider/
- http://blog.mist.io/post/82383668190/move-fast-and-dont-break-things-testing-with
- http://thechangelog.com/ansible-docker/
- http://devo.ps/blog/2013/09/25/vagrant-docker-and-ansible-wtf.html
- http://developer-blog.cloudbees.com/2014/02/using-jenkins-with-docker.html
- https://wiki.jenkins-ci.org/display/JENKINS/Docker+build+publish+Plugin
- http://www.nuxeo.com/blog/development/2014/02/docker-jenkins-cloud-provider/
- https://wiki.jenkins-ci.org/display/JENKINS/Docker+Plugin
- http://softwarefromnorth.blogspot.com/2014/04/self-registering-jenkins-hosts-with.html
- http://blog.howareyou.com/post/62157486858/continuous-delivery-with-docker-and-jenkins-part-i
- http://blog.howareyou.com/post/65048170054/continuous-delivery-with-docker-and-jenkins-part-ii

**Comment by KingOfPoptart** [comment]
PRD can be viewed here:
https://docs.google.com/document/d/1-2qD12dkfjJGAeh-nTvDHK_9tIDP2So6D1PLwgVxspw/edit?usp=sharing

**Comment by KingOfPoptart** [comment]
@jeroldleslie is already working on this

**Comment by jeroldleslie** [comment]
@smorin or @KingOfPoptart I think this ticket was completed. Please review and close

**Comment by KingOfPoptart** [comment]
@jeroldleslie , no - this ticket is to make a Jenkins plugin.  We can discuss more later, but for now I'm moving this into the backlog

**Comment by jeroldleslie** [comment]
ok
