### ISSUE TITLE
Developer-setup setup.sh fails in some Ubuntus

### ISSUE THREAD

**Issue by jclavijo** [DemandCube/NeverwinterDP_Legacy#178]
Setuo.sh has problems with Ubuntu install
setup.sh fails because os_meta_info.sh is unable to get the correct OS_DISTRO if using a Linux version and multiple /etc/*-release files exist.

setup.sh gets errors if it doesn't install required installs but continues with the rest of setup for Ubuntu.

curl is not installed correctly and is required for easy_intall step

**Comment by smorin** [comment]
When do you think you'll have this fixed?

**Comment by KingOfPoptart** [comment]
@PROM3TH3U5 What's the status on this?
