### ISSUE TITLE
Error if there isn't any argument or option specified

### ISSUE THREAD

**Issue by mehikmat** [DemandCube/NeverwinterDP_Legacy#179]
In [vagrant-centos](https://github.com/DemandCube/vagrant-centos)
when I ran `./setup` without any argument or without any option then there was error.
But should display usage information if 
- there isn't any argument specified
- there isn't any option specified
- there is invalid option specified
- there is option without argument  specified

**Comment by mehikmat** [comment]
above issue has been fixed and now handles _above four conditions_
[Pull Request Link](https://github.com/DemandCube/vagrant-centos/pull/4)

**Comment by smorin** [comment]
Ill code review it

**Comment by smorin** [comment]
@mehikmat  please update on the Kanban and don't forget to add your self as assignee

**Comment by KingOfPoptart** [comment]
@mehikmat What's the status on this?

**Comment by KingOfPoptart** [comment]
Actually last I checked, vagrant-centos was fine.  Gonna go ahead and close this
