### ISSUE TITLE
KafkaSphere - get consumer meta-data from kafka

### ISSUE THREAD

**Issue by pieteradejong** [DemandCube/NeverwinterDP_Legacy#184]
scripts in /bin should offer some options. or, look at where consumers are registered.

by analogy, achieve same as phpMyAdmin: ability to present overview of system metadata

**Comment by smorin** [comment]
When you figure out where and how to get this data, please write it up and document in the KafkaSphere readme

**Comment by smorin** [comment]
Update in Kanban if you haven't already done so and assign to your self
