### ISSUE TITLE
investigate where to get connection information on kafka API

### ISSUE THREAD

**Issue by stites** [DemandCube/NeverwinterDP_Legacy#191]

**Comment by smorin** [comment]
What do you mean by this?

**Comment by stites** [comment]
sorry - just saw this: I meant that we need to find out where to get the zookeeper/topics/consumers/producer information for the API. The kafka API is pretty vast - taking a hint from the Offset Monitor, I think I've found what we need in:

kafka.api.OffsetRequest
kafka.api.PartitionOffsetRequestInfo
kafka.common.BrokerNotAvailableException
kafka.common.TopicAndPartition
org.apache.zookeeper.data.Stat
- then, at a later stage, we'll set up a consumer to do some real-time reads on a topic

**Comment by stites** [comment]
going to close this since i would consider it the "research phase" of #44 or #120
