### ISSUE TITLE
Review Prototype Code

### ISSUE THREAD

**Issue by tuan08** [DemandCube/NeverwinterDP_Legacy#193]
Hi, 

Please review my code at https://github.com/tuan08/NeverwinterDP. The code is in the branch feature/prototype(https://github.com/tuan08/NeverwinterDP/tree/feature/prototype/code).  You can check out and read the Readme.md for the build instructions.

**Comment by tuan08** [comment]
Please close this one , I replaced  this by the pull request

**Comment by smorin** [comment]
This is great, we use Issues with pull requests
