### ISSUE TITLE
Create a Cluster registration service

### ISSUE THREAD

**Issue by smorin** [DemandCube/NeverwinterDP_Legacy#198]
Clusters, should each have an identifier, ips and record ping location, number of nodes in the cluster service.  This service should be built on NeverwinterDP

**Comment by tuan08** [comment]
Hazelcast internally has itself the ping service and we can reuse it with our plugin listener,  the Member interface provides the UUID, ip, port..., the cluster interface to access the members, listen to the member join and leave ... I currently has a class ClusterMember that wrap this  hazelcast to prepare we need to change the communication layer.

I am thinking to create a Cluster Discovery or  Service Registry which is updated each time a member or a service of a member join or leave.
