### ISSUE TITLE
[Sparkngin] Move to use Netty

### ISSUE THREAD

**Issue by tuan08** [DemandCube/NeverwinterDP_Legacy#199]
I reviewed netty and it support http protocol, I think we can quickly move to use netty and remove vertx, it will avoid the works later.

**Comment by smorin** [comment]
Yes let's do that.

At first learning thought netty would take a long time but reading more.  I
think we can use it more quickly than I originally thought.
-Steve

**Comment by KingOfPoptart** [comment]
What component is this for?  @tuan08 Can you please rename this ticket "[component name] - Move to use Netty"

**Comment by tuan08** [comment]
Hi ,

it is done, I forget to close. The common netty code is in NeverwinterDP-Commons/netty and sparkngin reuse this code.
