### ISSUE TITLE
vagrant-ubuntu and vagrant-centos automated testing scripts

### ISSUE THREAD

**Issue by smorin** [DemandCube/NeverwinterDP_Legacy#2]
So far following are the steps which are sufficient to verify the images.
1. vagrant box add box_name box_url     // adds image to vagrant
2. mkdir ~/test_project_dir && cd test_project_dir              // go to test project directory
3. vagrant init box_name      // creates Vagrantfile for above box
4. vagrant up                   // run image
5. vagrant ssh              // login to image instance
6. cd /vagrant/your_shared_dir        // go to shared directory
7. echo "Hello From Vagrant" > test_file.txt        // create a file 
8. sudo su -        // switch to root user
9. logout        // got to host system by logging out
10. got to host system and cd your_shared_directory  // got shared folder in host file system
11. cat test_file.txt  // view the vagrant shared file
      Hello From Vagrant
12. echo "Hello From Host" > test_file1.txt   // create file from host system
13. vagrant ssh        // login
14. cd /vagrant/your_shared_directory  // go to shared folder   for two-way share verification
15. cat test_file1.txt       // view host shared file
    Hello From Host

**Comment by mehikmat** [comment]
Implemented these steps in python according to QA-NeverwinterDP testing framework and sent a pull request for review

**Comment by smorin** [comment]
Since this is in code review please put the link to the pull request in the ticket.

**Comment by mehikmat** [comment]
This is the link to pull request for this ticket:
https://github.com/DemandCube/QA-NeverwinterDP/pull/10

**Comment by smorin** [comment]
@KingOfPoptart can you review this one?

**Comment by KingOfPoptart** [comment]
Looks like you're missing the assertion to check if Testfile.txt gets created locally on the host.  Since Testfile.txt is created in the shared folder, you should see it on the host machine - so add an assertion for that.  (Requirement 10-11)

You're also missing tests for testing if making a file on the host can be seen in the guest's shared folder (requirements 12-15)

You're missing a test to make sure su works (Requirement 8-9) - might be tricky though, I know dealing with su/sudo can be a pain programmatically.

**Comment by mehikmat** [comment]
will add those assertions soon

**Comment by mehikmat** [comment]
added assertions for 
1) checking file creation in host system
2) checking file creation in guest system
3) checking sudo access 
I have run whole image testing script in along with these assertions in my machine and all went fine.

Please review....

**Comment by KingOfPoptart** [comment]
Reviewed and merged

**Comment by smorin** [comment]
Thanks

**Comment by smorin** [comment]
Where is the pull request link?

**Comment by smorin** [comment]
Ignore my last comment I am going through old emails in order

**Comment by mehikmat** [comment]
:)

On Sun, Apr 20, 2014 at 1:26 PM, Steve Morin notifications@github.comwrote:

> Ignore my last comment I am going through old emails in order
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/DemandCube/NeverwinterDP/issues/2#issuecomment-40889805
> .

## 

_Hikmat Dhamee, Software Engineer | Kathmandu,Nepal |
me.hemant.available@gmail.com me.hemant.available@gmail.com |
+977-9848751308 | SKYPE: talk_hemant | whiteboxdeveloper.blogspot.com
http://whiteboxdeveloper.blogspot.com_
