### ISSUE TITLE
hdp-single-node-cluster

### ISSUE THREAD

**Issue by smorin** [DemandCube/NeverwinterDP_Legacy#201]
Use the instructions in the wiki page to create a shell script that will install a Single node cluster on a machine, using a makefile.

`./install`

Save the script to the repo:
    https://github.com/DemandCube/hdp-single-node-cluster

https://cwiki.apache.org/confluence/display/AMBARI/Blueprints#Blueprints-PreparingYourAmbariServerandAgents

**Comment by anthonyms** [comment]
Closed. 
Solved by https://github.com/DemandCube/hadoop-single-node-cluster/pull/10

**Comment by smorin** [comment]
Yup
