### ISSUE TITLE
Wrapper Script for DemandSpike

### ISSUE THREAD

**Issue by louzar** [DemandCube/NeverwinterDP_Legacy#203]
1) Define what demandspike commandline will do:
2) Write documentation for commandline script
3) Implement documentation
4) Update documentation as necessary.

demandspike -target targettype:units [protocol://host1:port/target] [protocol://host1:port/target]

// In this example it should connect to the local hadoop finding the default configs using the default user

e.g. 
demandspike -target msg:1000 http://webserver1.com:8080/service/1/ http://webserver1.com:8080/service/1/ http://webserver1.com:8080/service/1/

// Same as above example but with kafka

e.g. 
demandspike -target msg:1000 kafka://kafkaserver1.com:8080/topic1 kafka://kafkaserver2.com:8080/topic2/partition2/ kafka://kafkaserver3.com:8080/topic1

// In this example demandspike is running standalone against kafka

e.g. 
demandspike standalone -target msg:1000 kafka://kafkaserver1.com:8080/topic1 kafka://kafkaserver2.com:8080/topic2/partition2/ kafka://kafkaserver3.com:8080/topic1

TODO:
  Define arguments and what they do and what defaults they should have if not specified

  -output-dir (where output should go when a run completes)
  -output-type (if output is a csv maybe or defaults to console if not set)

  What are the targettype (io per second, messages per second, error rate greater than 20 % etc)

  What are the units for each target type?

  -mode (fixed or continous)

**Comment by smorin** [comment]
This should allow for running standalone and distributed and you can set things like configuration files and parameters to run a test.

**Comment by KingOfPoptart** [comment]
@louzar Status? Should this be reassigned?

**Comment by louzar** [comment]
this already done by Tuan, he wrapped demandspike by using Js file
