### ISSUE TITLE
DemandSpike playbook

### ISSUE THREAD

**Issue by louzar** [DemandCube/NeverwinterDP_Legacy#207]
Please include instructions to set this up using https://github.com/DemandCube/DeveloperPlayBooks

**Comment by smorin** [comment]
What is this for?  It's only a 1 word ticket in the title?

**Comment by smorin** [comment]
Please fix and add a better title and description or close

**Comment by louzar** [comment]
Something went wrong, I fix it

2014-05-23 15:51 GMT+01:00 Steve Morin notifications@github.com:
