### ISSUE TITLE
DemandSpike load test producer for sparkengin

### ISSUE THREAD

**Issue by louzar** [DemandCube/NeverwinterDP_Legacy#209]

**Comment by smorin** [comment]
Where is the link to the pull request?

**Comment by louzar** [comment]
same thing for issue #53,#54 , pull request is here https://github.com/DemandCube/DemandSpike/pull/2/files
Since that Tuan merged his code into DemandSpike, I forked demandSpike again from demandCube/demandspike and move it my source code to https://github.com/louzar/DemandSpikeOld
