### ISSUE TITLE
Create ansible role for installing zip

### ISSUE THREAD

**Issue by anthonyms** [DemandCube/NeverwinterDP_Legacy#210]
Needed by #202.

**Comment by anthonyms** [comment]
@KingOfPoptart Please review this PR.
https://github.com/artfullyContrived/DeveloperPlayBooks/pull/2

**Comment by smorin** [comment]
@artfullyContrived looks good but are you trying to merge to the `DemandCube` repo or your own.  I think you made a mistake here

**Comment by anthonyms** [comment]
Corrected.

Here is the correct PR.
https://github.com/DemandCube/DeveloperPlayBooks/pull/8
