### ISSUE TITLE
DemandSpike - Merging distributed metrics

### ISSUE THREAD

**Issue by louzar** [DemandCube/NeverwinterDP_Legacy#214]
first document all the metrics that we have in the issues/written about (a comprehensive collection of them) and put them in 1 place the DemandSpike PRD.  Each one should be defined in detail, what is it.  What is it capturing.
are you using codehale, or your own metrics?
What fields are you exposing? 
If your using codehale are you proposing using things like averages of the averages?
What field and data would you use for the averaging?
Then let's look at Hazelcast as a way to share distributed metrics and then use that as a mechanism to gather those metrics in more detail.
focus on research for the merging formula and provide some unit test for your formula

**Comment by KingOfPoptart** [comment]
What's the status on this @louzar ?

**Comment by KingOfPoptart** [comment]
Reassigning to @smorin

**Comment by smorin** [comment]
I am going to review all your old work on Distributed Metrics and consolidate it.

For percentiles I am looking at distributed algorithms to solve it.

**Comment by tuan08** [comment]
This should be replaced by issue #330
