### ISSUE TITLE
Modify the oracle_jdk ansible playbook to set JAVA_HOME

### ISSUE THREAD

**Issue by anthonyms** [DemandCube/NeverwinterDP_Legacy#216]
Thoughts anyone?

**Comment by tuan08** [comment]
Depends on the linux distro, you can modify /etc/rc.locale and add the export $JAVA_HOME instruction. On macos , I use export JAVA_HOME=$(/usr/libexec/java_home). If you want to set the java home for a specific user  only , you need to update  /home/username/.bashrc or  .bash_profile

**Comment by anthonyms** [comment]
The current script only targets centos/RHEL. Its downloads an rpm file and uses yum.
For a start we could just add it for the current user only

**Comment by smorin** [comment]
What application needs JAVA_HOME set?

**Comment by anthonyms** [comment]
I encountered the need while installing gradle.

**Comment by KingOfPoptart** [comment]
@artfullyContrived what's the status on this issue?

**Comment by anthonyms** [comment]
Not sure if to close or pursue further. It needs consensus from the team. 
I have needed $JAVA_HOME when using gradle, and when running the scripts in DemandSpike.

@tuan08 most of the scripts in demandspike require $JAVA_HOME. I've had to manually set it up.
Wouldn't this solve the problem permanently?

**Comment by tuan08** [comment]
Why this task is assigned to me, I do not have an idea what is going on

**Comment by KingOfPoptart** [comment]
@artfullyContrived if its an issue, go ahead fix the problem yourself.  Will there be any negative impact for setting this variable?

**Comment by smorin** [comment]
Anthony is this blocking you?  I am not sure why this was opened

**Comment by anthonyms** [comment]
Ill close it.  Seems like there's no need fir $JAVA_HOME
