### ISSUE TITLE
single-node-hadoop-setup - test, fix and add unittests

### ISSUE THREAD

**Issue by smorin** [DemandCube/NeverwinterDP_Legacy#217]
1) Retest and fix if necessary the single-node-hadoop-setup in AWS ( I can give you a machine let me know when) and digitalocean on Centos 6.5.
To replicate digitalocean you can start by testing on a VM with CentOS 6.5
2) Add unit test like I described in the email
3) will be to add to jenkins

Can you look at getting this to work on a node/vm (CentOS 6.5 minimal) with out a full qualified domain name (fqdn) (so has a hostname but it's not listed in a real dns setup)  

Current Known Issue:
https://github.com/DemandCube/hadoop-single-node-cluster/issues/5

The repo:
https://github.com/DemandCube/hadoop-single-node-cluster

Initial tests 

Peter part of next steps after the unit test will be to setup the unittests
Part 1
  unittest
Part 2
  Setup in jenkins 
  a) on pull requests
  b) on commits
  c) nightly

When installed in jenkins these tests should run in docker

**Comment by jeroldleslie** [comment]
Hi steve,

Found root cause of the problem,

Ambari looks hostname of the machine in /etc/sysconfig/network which has entry like  "HOSTNAME=localhost.localdomain”
have to set hostname in the agent machine. 
I will do fix in create_cluster.sh

Also in the issue DemandCube/hadoop-single-node-cluster#5, Cluster is duplicated. i.e., cluster is already created there, we can add delete command before creating cluster for testing pupose.

curl -v -X DELETE http://admin:admin@localhost:8080/api/v1/clusters/cl1 --header "Content-Type:application/json" --header "X-Requested-By:mycompany”

I need AWS and digitalocean on Centos 6.5 access details to test this single-node-hadoop setup after my fix.

**Comment by smorin** [comment]
Okay send me your ssh key and I'll get you a digital ocean and AWS machine
to test with.
-Steve

On Wed, Jun 11, 2014 at 11:16 AM, Peter Jerold Leslie <
notifications@github.com> wrote:

> Hi steve,
> 
> Found root cause of the problem,
> 
> Ambari looks hostname of the machine in /etc/sysconfig/network which has
> entry like "HOSTNAME=localhost.localdomain”
> have to set hostname in the agent machine.
> I will do fix in create_cluster.sh
> 
> Also in the issue DemandCube/hadoop-single-node-cluster#5, Cluster is
> duplicated. i.e., cluster is already created there, we can add delete
> command before creating cluster for testing pupose.
> 
> curl -v -X DELETE http://admin:admin@localhost:8080/api/v1/clusters/cl1
> --header "Content-Type:application/json" --header
> "X-Requested-By:mycompany”
> 
> I need AWS and digitalocean on Centos 6.5 access details to test this
> single-node-hadoop setup after my fix.
> 
> On 10-Jun-2014, at 11:10 pm, Steve Morin notifications@github.com
> wrote:
> 
> > 1) Retest and fix if necessary the single-node-hadoop-setup in AWS ( I
> > can give you a machine let me know when) and digitalocean on Centos 6.5.
> > To replicate digitalocean you can start by testing on a VM with CentOS
> > 6.5
> > 2) Add unit test like I described in the email
> > 3) will be to add to jenkins
> > 
> > Can you look at getting this to work on a node/vm (CentOS 6.5 minimal)
> > with out a full qualified domain name (fqdn) (so has a hostname but it's
> > not listed in a real dns setup)
> > 
> > Current Known Issue:
> > DemandCube/hadoop-single-node-cluster#5
> > 
> > The repo:
> > https://github.com/DemandCube/hadoop-single-node-cluster
> > 
> > Initial tests
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/DemandCube/NeverwinterDP/issues/217#issuecomment-45755354
> .

## 

Steve Morin | Hacker, Entrepreneur, Startup Advisor
twitter.com/SteveMorin | stevemorin.com
_Live the dream start a startup. Make the world ... a better place._

**Comment by jeroldleslie** [comment]
digital ocean and AWS machine is ready?

**Comment by smorin** [comment]
Yes

**Comment by jeroldleslie** [comment]
@smorin I think this was completed
