### ISSUE TITLE
single-node-hadoop-setup - add check to see if ambari thinks cluster or blueprint are already installed

### ISSUE THREAD

**Issue by smorin** [DemandCube/NeverwinterDP_Legacy#219]
Add check to see if the blueprint or cluster are already installed

---

ambari cannot yet run on ubuntu. 
See the links below.

https://cwiki.apache.org/confluence/display/AMBARI/Quick+Start+Guide
https://issues.apache.org/jira/browse/AMBARI-1241

The error occurs when one attempts to create a cluster a second time by hitting the same cluster url more than once.
i.e curl -v -X POST -d @cluster-creation.json http://admin:admin@localhost:8080/api/v1/clusters/cl1 . . . 

Please confirm that you didn't get the error on the first run of the script.
A solution is to change the cluster name from cl1 to cl2 for the second run.

**Comment by anthonyms** [comment]
This appears to be 2 separate issues.
1. check if blueprint already exists
2. check if cluster already exists.

The PR for the second issue is https://github.com/DemandCube/hadoop-single-node-cluster/pull/8.

This prevents the following error 

```
{
  "status" : 409,
  "message" : "Attempted to create a Cluster which already exists, clusterName=cl1"
* Connection #0 to host localhost left intact
* Closing connection #0
}
```

**Comment by smorin** [comment]
I have solved this

**Comment by jeroldleslie** [comment]
Hi Steve,
On running INSTALL-HADOOP  on jenkins with docker it fails with

"WARNING NOT ENOUGH MEMORY
RAM=1011564 kilobytes
NOTE: 1 gig of ram is 1048576 kilobytes

RECOMMENDED: Minimum of 4 Gigs of RAM or will probably fail”

because  only 1011564 kilobytes memory is allocated with docker. Also it fails in digital ocean (only 512mb allocated memory).

**Comment by smorin** [comment]
Yes I have figured that out and will have to use larger machines in digital
ocean from now on.
-Steve

On Mon, Jun 16, 2014 at 2:13 AM, Peter Jerold Leslie <
notifications@github.com> wrote:

> Hi Steve,
> On running INSTALL-HADOOP on jenkins with docker it fails with
> 
> "WARNING NOT ENOUGH MEMORY
> RAM=1011564 kilobytes
> NOTE: 1 gig of ram is 1048576 kilobytes
> 
> RECOMMENDED: Minimum of 4 Gigs of RAM or will probably fail”
> 
> because only 1011564 kilobytes memory is allocated with docker. Also it
> fails in digital ocean (only 512mb allocated memory).
> 
> On 16-Jun-2014, at 2:33 pm, Steve Morin notifications@github.com wrote:
> 
> > I have solved this
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/DemandCube/NeverwinterDP/issues/219#issuecomment-46156581
> .

## 

Steve Morin | Hacker, Entrepreneur, Startup Advisor
twitter.com/SteveMorin | stevemorin.com
_Live the dream start a startup. Make the world ... a better place._

**Comment by tuan08** [comment]
Hi,

I run into this problem too.  For testing , I think a VM with 2GB should be enough. We should be able to set  max memory heap 128MB for each java process.

**Comment by jeroldleslie** [comment]
Hi Steve,

I am getting this error while installing hadoop single node cluster.
"glibc detected **\* /usr/bin/python: malloc()”
looks like memory allocation problem. Tried with low memory in docker/VM, getting this error. The same error getting in digital ocean box. I think its because memory allocation problem with low memory of VM.

**Comment by smorin** [comment]
Yes that is, did you update your code from the repo? Over the weekend I added a memory check.  You need a min of 4gig of ram to successfully run the program

**Comment by jeroldleslie** [comment]
My machine having memory of 4GB. So I can only allocate 1GB memory to VM/ docker container runs in my machine. So I cannot able to test with docker image or VM.
