### ISSUE TITLE
Modify gradle role to allow gradle binary  instantly accessible.

### ISSUE THREAD

**Issue by anthonyms** [DemandCube/NeverwinterDP_Legacy#220]
The current gradle role adds the gradle binary to the path by 

```
source /etc/profile.d/gradle.sh
```

the gradle.sh file adds gradle/bin to the path.

Adding gradle this way doesn't make it accessible to jenkins.

The proposed change adds gradle to /usr/bin/gradle as a symbolic link.

**Comment by anthonyms** [comment]
PR available at https://github.com/DemandCube/DeveloperPlayBooks/pull/11.

**Comment by smorin** [comment]
I added a comment, should the old code be cleaned up if your adding this
mechanism?

**Comment by anthonyms** [comment]
Closed. 
Solved by https://github.com/DemandCube/DeveloperPlayBooks/pull/11
