### ISSUE TITLE
Move github-reporter jenkins job to production server.

### ISSUE THREAD

**Issue by anthonyms** [DemandCube/NeverwinterDP_Legacy#223]
The following are the expected steps.
1. Run the Push_Jenkins_CI_Changes job on the production server.
2. Re-run the jenkins ansible role on the jenkins test server to update the configs.
3. Down grade the jenkins version to 1.570-1.1 because of https://issues.jenkins-ci.org/browse/JENKINS-22550. (Production server uses jenkins version 1.570). 
4. update the github-reporter job following the instructions at https://github.com/DemandCube/TeamWiki/wiki/Github-reporter-setup-instructions. Only steps 12 onwards are needed..
5. Create a tag in jenkins-config for the current state.
6. Document the steps in the team wiki https://github.com/DemandCube/TeamWiki/wiki.
7. Execute the gradle job on the production server, update the github-reporter job and go live on production server.
8. Stop the jenkins service on the demo server.

Each action point is estimated to take a maximum of 1 hour.

**Comment by KingOfPoptart** [comment]
I think step 1 should actually be the last step, I don't think there's a point to running that job if no changes have been made yet

**Comment by smorin** [comment]
3) Is that upgrade or downgrade, by version number listed it seems to be a upgrade.

@KingOfPoptart do you approve of this plan?

@jeroldleslie be part of this thread since your also working on using the Jenkins workflow

**Comment by KingOfPoptart** [comment]
I commented on the issue already, I think one of the steps is misplaced

**Comment by anthonyms** [comment]
@KingOfPoptart The intention of running the job as the first item is to save the current configuration. Thus in case things go wrong we have a restore point.

However, we should also run it as the last item as well so that the updated configs for the github-reporter are saved.

**Comment by anthonyms** [comment]
@smorin point 3 is a downgrade but I typed in the version numbers wrong.

Running the jenkins ansible role installs the latest jenkins version (currently 1.570-1.1).
The production server uses version 1.557.  According to the jira issue versions > 1.557 have problems with the github plugin.

Note that the jenkins role will not be run on the production server.

**Comment by anthonyms** [comment]
Interestingly the latest version of jenkins (1.571)  works well with the gradle plugin.

**Comment by KingOfPoptart** [comment]
Is this done @artfullyContrived ?

**Comment by anthonyms** [comment]
github-reporter is now running on jenkins.demandcube.com.
Documentation is now under #239

**Comment by anthonyms** [comment]
@KingOfPoptart 
I do not have permissions to create new tags in Jenkins-configs.
Everything else is done.

**Comment by anthonyms** [comment]
@KingOfPoptart
Either permissions to create new tags in jenkins-configs.
Or you create the tags

**Comment by KingOfPoptart** [comment]
Assigning to @smorin since he's the man with permissions control

**Comment by KingOfPoptart** [comment]
@artfullyContrived I've created a tag for you, not sure if its what you needed since I don't have permission to allow you to create tags

https://github.com/DemandCube/Jenkins-configs/releases/tag/1.0

**Comment by anthonyms** [comment]
This thus finalises the ticket.

**Comment by anthonyms** [comment]
@KingOfPoptart 
PR for NullPointerException in issue.getClosedBy().
https://github.com/DemandCube/github-reporter/pull/6

**Comment by KingOfPoptart** [comment]
@artfullyContrived, can we close this issue?

**Comment by anthonyms** [comment]
Yes.  This has been done.
