### ISSUE TITLE
Add more properties to kafka producer

### ISSUE THREAD

**Issue by louzar** [DemandCube/NeverwinterDP_Legacy#227]
private int requiredAcks = 1;
  private int compressionCodec = 1;
  private int sendBufferBytes = 65536;
  private String producerType = "async";
  private int batchNumMessages = 200;
  private int enqueueTimeout = -1;
  private String clientId;
  private int requestTimeout = 6000;
  private int sendMaxRetries = 3;
  private int retryBackoff = 300;

**Comment by tuan08** [comment]
Hi Nizar,

Where do you plan to add ? The kafka configuration is in properties format , why do you want to convert to the native. I already add the producer configuration here is how to configure the message driver or  kafka producer:

 var jobParams = {
    //test kafka with 1k message size
    "driver": "kafka", "driver:request.required.acks": "1",
    "broker-connect": KAFKA_CONFIG.kafkaConnect, "topic": "metrics.consumer",
    "num-of-task": 2, "num-of-thread": 2, "message-size": 1024,
    "member-role": "demandspike", "max-duration": 60000, "max-num-of-message": 3000000,
    "problem:kafka.problem": "service-failure",
    "problem:kafka.member-role": "kafka",
    "problem:kafka.module": "Kafka",
    "problem:kafka.service-id": "KafkaClusterService",
    "problem:kafka.period": "15000",
    "problem:kafka.failure-time": "1000"
  }

The important is you have to understand exactly the behavior of  each parameter. For example , if you turn on/off  request.required.acks  , you may get 3x different in performance. That result I get when I run kafka performance unit test code standalone. But when I run DemandSpike , I do not see any different. I don't know what is wrong yet

**Comment by louzar** [comment]
I'm testing with DemandSpikeAppContainerUnitTest like this for example : 

```
String[] args = { 
  "--mini-cluster-env",
  "--app-name", "NeverwinterDP DemandSpike App",
  "--container-manager", "com.neverwinterdp.demandspike.yarn.AsyncDemandSpikeAppContainerManager",
  "--conf:yarn.resourcemanager.scheduler.address=0.0.0.0:8030",
  "--conf:demandspike.instance.core=1",
  "--conf:demandspike.instance.memory=128",
  "--conf:demandspike.job.num-of-task=3",
  "--conf:demandspike.job.driver=kafka",
  "--conf:demandspike.job.topic=" + DemandSpikeClusterBuilder.TOPIC ,
  "--conf:demandspike.job.broker-connect=" + clusterBuilder.getKafkaConnect(),
  "--conf:demandspike.job.max-duration=25000",
  "--conf:demandspike.job.requiredAcks=-1",
  "--conf:demandspike.job.compressionCodec=snappy",
  "--conf:demandspike.job.sendBufferBytes=65536",
  "--conf:demandspike.job.producerType=async",
  "--conf:demandspike.job.batchNumMessages=200",
  "--conf:demandspike.job.enqueueTimeout=-1",
  "--conf:demandspike.job.clientId=producer",
  "--conf:demandspike.job.requestTimeout=6000",
  "--conf:demandspike.job.sendMaxRetries=3",
  "--conf:demandspike.job.retryBackoff=300"
} ;
```

I'm testing with different combinations and I'm seeing some differences until now.

**Comment by tuan08** [comment]
Nizar ,

I replied that I already add the kafka producer properties capabilities to the command and I am rewritting a lot of demandspike code.  The problem with your code is  you do not support all the kafka producer properties and the properties may change in the future. Another problem is we have different driver with the completely different  properties name, for example the sparkngin driver. You can use your code to do the research and report what are the problems or performance with the different configuration

**Comment by louzar** [comment]
yes I saw your email. Now that your code support all proprieties do you
want me to do some test with different combinations of these properties or
do you have prior task for me.

Nizar

2014-07-17 8:30 GMT+01:00 Tuan Nguyen notifications@github.com:
