### ISSUE TITLE
Update Jenkins-configs to launch master and slave configuration using vagrant-flow

### ISSUE THREAD

**Issue by KingOfPoptart** [DemandCube/NeverwinterDP_Legacy#228]
Once the ansible roles are defined and working, we need to be able to launch the master/slave jenkins environment seamlessly in one step.  Make sure when we launch setup_virtualBox.sh and setup_digitalOcean.sh, we now launch the master/slave setup

You'll need to update multiinitconfig.yml and groupconfig.yml to do this.  (I don't think you'll need to change much else)

Refer to https://github.com/DemandCube/vagrant-flow for how vagrant flow works.

**Comment by KingOfPoptart** [comment]
Naming conventions:

Slave machines brought up in prod should be named

```
slave1.jenkins
slave2.jenkins
etc...
```

That way they can be found on DNS as slave1.jenkins.do.demandcube.com

**Comment by jeroldleslie** [comment]
Hi richard,
I need to get ready master and slave machines for jenkins production environment. If jenkins master and slaves already exists please give me the details to configure in inventory file and variables file.
If it doesn’t exists please create it as soon as possible. 

Details needed to configure in inventory file and group variable file
1. Inventory 

jenkins master name 
list of jenkins slave name
1. Group variables
   jenkins_master_url: <jenkins master url>
   jenkins_username: <username of jenkins master>
   jenkins_password: <password of jenkins master >
   jenkins_master_sshPublicKey: <jenkins master public ssh to enable passwordless communication between master and slaves>

Regards,
Peter Jerold Leslie
jeroldleslie@gmail.com

**Comment by KingOfPoptart** [comment]
The jenkins master will be named jenkins (for continuity for the website).  Slaves will be named slave1.jenkins, slave2.jenkins, etc

For now lets just define jenkins and slave1.jenkins, we need to think of an intelligent want to automatically expand jenkins slaves, or just expand when we need to.

You don't need to manually create the inventory files.  Vagrant-flow will take care of that https://github.com/DemandCube/vagrant-flow#ansibleinventory

Group variables - 
jenkins_master_url - what's the point of this?  If you create a machine on digital ocean named jenkins, the DNS will automatically pick it up as jenkins.demandcube.com, so just make sure the hostname is jenkins
jenkins_username/password/sshkey - The slaves should not need to ssh back onto the master.

**Comment by jeroldleslie** [comment]
But now I am not using vagrant-flow for master/slave setup of jenkins. As discussed with steve, the goal was to create master/slave without using vagrant-flow. So inventory files should be created manually with hosts.
We are using swarm plugin for slave creation. When starting the swarm client, it will connect to the master and the master will automatically create a new node for it. There are a couple of parameters to start the client. You still need to provided a login/password in order to authenticate. So username/password of jenkins is must (we can create detected user in jenkins for this).

Regards,
Peter Jerold Leslie
jeroldleslie@gmail.com

**Comment by KingOfPoptart** [comment]
This is the next step to set things up with vagrant-flow.  The vagrant-flow command "vagrant flow ansibleinventory" will automatically make your inventory file for you.  Go this route, and check in your inventory file as well if you feel that's needed based on your discussion with Steve.  My understanding is that we want the playbooks to work anywhere (which they will no matter what), but we also want to be able to launch machines with vagrant to create local VM's and publish the production machines to Digital Ocean.

If you feel there is a need to expand what vagrant-flow can do, then that's a discussion for vagrant-flow when we're post-alpha.

http://www.donaldsimpson.co.uk/2013/03/18/jenkins-slave-nodes-using-the-swarm-plugin/  <--I didn't see any need for a user/password for the swam plugin.  

By default, the jenkins username is a service account, it doesn't have a shell by design. It is generally accepted that service accounts shouldn't be able to log in interactively

**Comment by smorin** [comment]
Okay my thoughts

1) Can you guys find some time to get on a skype call "Please make this happen"
2) Peter please follow what Richard is saying.
3) Peter please explain why you need each credential and where to help clear up why they are necessary.

Goal have this run with Vagrant Flow AND With just Ansible directly

**Comment by KingOfPoptart** [comment]
This is fixed by issue #244
