### ISSUE TITLE
reconfigure test script and run until it has the error.

### ISSUE THREAD

**Issue by louzar** [DemandCube/NeverwinterDP_Legacy#230]
analyze the log, code  and propose a solution for the missing part.

**Comment by smorin** [comment]
Great

**Comment by louzar** [comment]
I ran kafka producer for 1 min with different properties values, I noticed that the big difference is when we set ack to 1 , or when compression code is set or when we use async mode. The comparison between these 3 mode is in the spreadsheet below
https://docs.google.com/spreadsheets/d/1iklEDG4lLVCbolfUFiPRI3sJ8t6FkX1xyYEg6gXn_Mw/edit#gid=282904418

we notice that the throughput is important in async mode

**Comment by louzar** [comment]
I sent 3 Go with kafka produer  for 3 mode ( default, ack=1, async) with different message size, the result are in the spreadsheet below
https://docs.google.com/spreadsheets/d/1t9VKs-TiEPJTf8NW4GphE4-5_leWM3MKO2ORgSjmRrA/edit#gid=1821368712  

we notice that more the message size is bigger, more the errors appears

**Comment by louzar** [comment]
these are the errors that I have encounter when running demandspike jobs
https://drive.google.com/file/d/0By4fj0gFKZqGSHFfWDFfUks4cHM/edit?usp=sharing

**Comment by louzar** [comment]
I think we have to think about a ui for demandspike, specially to change producer proprieties and visualize metric in real time. here is my vision to how it will look like https://moqups.com/louzar/QeoO8rtn
![demandspike](https://cloud.githubusercontent.com/assets/1942640/3810970/3bf2486c-1c98-11e4-996d-1a77a2d91e6c.png)

**Comment by tuan08** [comment]
First , could you add more test script with gzip , snappy ... and check in ,  you can leave the script in nizar-kafka-test.js. I will review and merge your code

**Comment by louzar** [comment]
ok

**Comment by louzar** [comment]
done, pull request link is https://github.com/DemandCube/NeverwinterDP/pull/284

**Comment by KingOfPoptart** [comment]
What's the status on this ticket?

**Comment by louzar** [comment]
this is done the results are in the wiki
