### ISSUE TITLE
Update README for NeverwinterDP-Commons

### ISSUE THREAD

**Issue by KingOfPoptart** [DemandCube/NeverwinterDP_Legacy#232]
Ensure the documentation is up to date. 

Things to include:
1. Overall framework - how it works, what technologies do what, etc
2. How to build
3. Any available tests that exist
4. Any dependencies

**Comment by tuan08** [comment]
I add some document to the README.md

**Comment by tuan08** [comment]
You can update the doc, add TODO to the README if you feel certain part is not clear or missing
