### ISSUE TITLE
Update README for Sparkngin

### ISSUE THREAD

**Issue by KingOfPoptart** [DemandCube/NeverwinterDP_Legacy#234]
Ensure the documentation is up to date.

Things to include:
1. Overall framework - how it works, what technologies do what, etc
2. How to build
3. Any available tests that exist
4. Any dependencies

**Comment by tuan08** [comment]
Hi,

I add the new README-NEW.md file as the README.md contains some outdated information. Please review with Steve and merge 2 files

**Comment by KingOfPoptart** [comment]
@tuan08 Go ahead and merge the two files yourself please
