### ISSUE TITLE
Update README for Scribengin

### ISSUE THREAD

**Issue by KingOfPoptart** [DemandCube/NeverwinterDP_Legacy#235]
Ensure the documentation is up to date.

Things to include:
1. Overall framework - how it works, what technologies do what, etc
2. How to build
3. Any available tests that exist
4. Any dependencies

**Comment by tuan08** [comment]
I think Lih should work on this document

**Comment by KingOfPoptart** [comment]
@tuan08 next time feel free to reassign it yourself.
