### ISSUE TITLE
Update README for Demandspike

### ISSUE THREAD

**Issue by KingOfPoptart** [DemandCube/NeverwinterDP_Legacy#236]
Ensure the documentation is up to date.

Things to include:
1. Overall framework - how it works, what technologies do what, etc
2. How to build
3. Any available tests that exist
4. Any dependencies

**Comment by tuan08** [comment]
I already add some doc to DemandSpike Readme

**Comment by louzar** [comment]
I added new section to the documentation : how to run demandspike job
pull request https://github.com/DemandCube/DemandSpike/pull/6
