### ISSUE TITLE
Update README for NeverwinterDP

### ISSUE THREAD

**Issue by KingOfPoptart** [DemandCube/NeverwinterDP_Legacy#237]
Ensure the documentation is up to date.

Things to include:
1. Overall framework - how it works, what technologies do what, etc
2. How to build
3. Any available tests that exist
4. Any dependencies

**Comment by tuan08** [comment]
Steve + Richard,

please review  the NeverwinterDP-Commons, Queuengin , Sparkngin and DemandSpike  README.md and README-NEW.md file. You can reorganize and merge with the old README. If you need me to write more about the design  , add TODO to the README.md file

**Comment by KingOfPoptart** [comment]
@tuan08 , in the future please submit the links for pull requests and don't do the merge into the master branch yourself.

Did you update https://github.com/DemandCube/NeverwinterDP/blob/master/README.md ?  Or do you not need to?

**Comment by KingOfPoptart** [comment]
Also I noticed no tests were documented.  Does any of your code include unit testing or any other kind of testing apart from using DemandSpike?
