### ISSUE TITLE
Update documentation for github-reporter

### ISSUE THREAD

**Issue by KingOfPoptart** [DemandCube/NeverwinterDP_Legacy#239]
Ensure the documentation is up to date.

Things to include:
1. Overall framework - how it works, what technologies do what, etc
2. How to build
3. Any available tests that exist
4. Any dependencies

**Comment by anthonyms** [comment]
This has two parts to it.
1. Update a readme file for github-reporter
2. update the wiki.

**Comment by anthonyms** [comment]
@KingOfPoptart 
PR for readme file https://github.com/DemandCube/github-reporter/pull/5

**Comment by anthonyms** [comment]
@KingOfPoptart  or @smorin 
Kindly review https://github.com/DemandCube/TeamWiki/wiki/Github-reporter-setup-instructions.

If all is ok.  We close this.

**Comment by KingOfPoptart** [comment]
https://github.com/DemandCube/TeamWiki/wiki/Github-reporter-setup-instructions  doesn't seem to have anything in it.

**Comment by KingOfPoptart** [comment]
My only qualm is that there are a significant number of dependencies involved  - guava, gson, etc - but no instructions nor scripts on how to install them.  Are these dependencies taken care of by any sort of setup script?

**Comment by KingOfPoptart** [comment]
@artfullyContrived , please update the link so that there is no trailing "." character at the end of the link

**Comment by KingOfPoptart** [comment]
Why is one of the steps to copy from https://github.com/artfullyContrived/DemandCubePlaybooks/blob/wikilinks/play.yml  <-- I don't think one of the steps should point to your personal repository.  Why isn't this being checked into the master DemandCube branches?

**Comment by KingOfPoptart** [comment]
Also please include screenshots for navigating through Jenkins and for configuring the job on the wiki

**Comment by anthonyms** [comment]
@KingOfPoptart 
The dependencies are pulled in by gradle for free.
Trailing '.'  has been removed.

The rest I'll action ASAP.

**Comment by smorin** [comment]
#218 See old requirements

**Comment by anthonyms** [comment]
@KingOfPoptart 
Below is the PR for getting the play.yml file into DemandCubePlaybooks.  Once approved, ill update the link. In the wiki.
https://github.com/DemandCube/DemandCubePlaybooks/pull/13

**Comment by anthonyms** [comment]
PR for screen shots.
https://github.com/DemandCube/TeamWiki/pull/1

Currently wiki has  images located in my local repository for viewing.
