### ISSUE TITLE
Document how to set up new unit tests in Jenkins using Docker on a Jenkins Slave

### ISSUE THREAD

**Issue by KingOfPoptart** [DemandCube/NeverwinterDP_Legacy#241]
Document the process to setup new tests/jobs and run these tasks on a Jenkins slave in docker
- to run the job nightly 
- to run on a pull request
- to run on pushes 

Screenshots will be very helpful to document this process since Jenkins is a UI tool

**Comment by jeroldleslie** [comment]
Doc added in https://github.com/DemandCube/TeamWiki/wiki/CI-using-jenkins-and-dockers. @KingOfPoptart please review it
