### ISSUE TITLE
Scribengin - Anthony Requirements

### ISSUE THREAD

**Issue by smorin** [DemandCube/NeverwinterDP_Legacy#242]

**Comment by anthonyms** [comment]
From the email

Background:
- Transactional write to HDFS
  -- Keep writing to a temp file (let's call it datalog) until the checkpoint timer goes off.
  -- When the checkpoint timer goes off.
  1. Write to the commit log (Note that this is different from the datalog. Let's call it the commit log) what's about to do. See ScribeLogEntryTest.java for more examples.
     a. startOffset
     b. endOffset
     c. srcPath
     d. destPath
     e. checksum
     -- mv the file from srcPath to destPath. Note that mv is atomic. Either the move command is completed, or it is npot at all. You can't have a file that's partially moved.
- Recovery
  -- See ScribeConsumer::getLatestOffsetFromCommitLog()
  -- When ScribeConsumer comes back online, it checks the commitlog to see what the state of the world is before it went again.

**Comment by anthonyms** [comment]
Allow ScribeConsumer to react to leader change in kafka.  Also allow it to respond to leader connection fail.

**Comment by anthonyms** [comment]
This belongs to @noitcudni as he determines suitable scribengin tasks.
I open separate tickests based on feedback placed here.
