### ISSUE TITLE
vagrant-flow - Ensure we can update production boxes in digital ocean using vagrant-flow

### ISSUE THREAD

**Issue by KingOfPoptart** [DemandCube/NeverwinterDP_Legacy#244]
Specifically talking about updating jenkinsdp and slave1Jenkins

Peter was seeing this error:
The provider for this Vagrant-managed machine is reporting that it
is not yet ready for SSH. Depending on your provider this can carry
different meanings. Make sure your machine is created and running and
try again. Additionally, check the output of `vagrant status` to verify
that the machine is in the state that you expect. If you continue to
get this error message, please view the documentation for the provider
you're using.

**Comment by KingOfPoptart** [comment]
@jeroldleslie Can you please review

**Comment by KingOfPoptart** [comment]
@jeroldleslie Its now ready to test again.

```
vagrant plugin install vagrant-digitalocean
git clone https://github.com/Demandcube/Jenkins-configs
cd Jenkins-configs
./setup_digitalOcean.sh
```

When it starts running the ansible scripts, you can go ahead and exit out.

**Comment by jeroldleslie** [comment]
going to review

**Comment by jeroldleslie** [comment]
@KingOfPoptart it was successful when executing ./setup_digitalOcean.sh and it starts ansible scripts. But this fix breaks virtualbox when executing ./setup_virtualBox.sh. 

Authentication error when running ./setup_virtualBox.sh

queuengin: Waiting for machine to boot. This may take a few minutes...
queuengin: SSH address: 127.0.0.1:2222
    queuengin: SSH username: vagrant
    queuengin: SSH auth method: private key
    queuengin: Warning: Connection timeout. Retrying...
    queuengin: Warning: Authentication failure. Retrying...
    queuengin: Warning: Authentication failure. Retrying...
    queuengin: Warning: Authentication failure. Retrying...
    queuengin: Warning: Authentication failure. Retrying...
...
...
...
it goes on...
