### ISSUE TITLE
[DemandCubePlaybooks] Jenkins slave role and ubuntu support

### ISSUE THREAD

**Issue by jeroldleslie** [DemandCube/NeverwinterDP_Legacy#246]
@smorin or @KingOfPoptart 
PR created https://github.com/DemandCube/DemandCubePlaybooks/pull/14
Jenkins slave and ubuntu support completed. Please review code and merge into master as soon as possible.

**Comment by smorin** [comment]
Peter what do you have next?

On Wed, Jul 23, 2014 at 3:26 PM, Richard Duarte notifications@github.com
wrote:

> Closed #246 https://github.com/DemandCube/NeverwinterDP/issues/246.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/DemandCube/NeverwinterDP/issues/246#event-144895214.

## 

Steve Morin | Hacker, Entrepreneur, Startup Advisor
twitter.com/SteveMorin | stevemorin.com
_Live the dream start a startup. Make the world ... a better place._

**Comment by jeroldleslie** [comment]
Codes are merged. So, need to Jenkins DemancubePlaybook ansible scripts in production. Can I run it today?

After this I am going to document all continues integration using jenkins docker stuffs (today and tomorrow). And create PR one by one.

Regards,
Peter Jerold Leslie
jeroldleslie@gmail.com

**Comment by smorin** [comment]
Yes you can deploy today.

Yes then continue with the Documentation where do you plan to put the
documentation?
-Steve

On Wed, Jul 23, 2014 at 11:18 PM, Peter Jerold Leslie <
notifications@github.com> wrote:

> Codes are merged. So, need to Jenkins DemancubePlaybook ansible scripts in
> production. Can I run it today?
> 
> After this I am going to document all continues integration using jenkins
> docker stuffs (today and tomorrow). And create PR one by one.
> 
> Regards,
> Peter Jerold Leslie
> jeroldleslie@gmail.com
> 
> On 24-Jul-2014, at 11:33 am, Steve Morin notifications@github.com
> wrote:
> 
> > Peter what do you have next?
> > 
> > On Wed, Jul 23, 2014 at 3:26 PM, Richard Duarte <
> > notifications@github.com>
> > wrote:
> > 
> > > Closed #246 https://github.com/DemandCube/NeverwinterDP/issues/246.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > > https://github.com/DemandCube/NeverwinterDP/issues/246#event-144895214>.
> > 
> > ## 
> > 
> > Steve Morin | Hacker, Entrepreneur, Startup Advisor
> > twitter.com/SteveMorin | stevemorin.com
> > _Live the dream start a startup. Make the world ... a better place._
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/DemandCube/NeverwinterDP/issues/246#issuecomment-49971375
> .

## 

Steve Morin | Hacker, Entrepreneur, Startup Advisor
twitter.com/SteveMorin | stevemorin.com
_Live the dream start a startup. Make the world ... a better place._

**Comment by jeroldleslie** [comment]
In https://github.com/DemandCube/TeamWiki/wiki I have planed to document.
Also in DemandCubePlaybook project for “Jenkins Installation using DemandcubePlaybook ansible script"

Regards,
Peter Jerold Leslie
jeroldleslie@gmail.com
