### ISSUE TITLE
[NeverWinterDP] Complete script test profile

### ISSUE THREAD

**Issue by tuan08** [DemandCube/NeverwinterDP_Legacy#249]
Add js script test for sparkngin , restart sparkngin, kafka... service to make sure the test has the clean environment.  Add service failure simulation for kafka , sparkngin

**Comment by tuan08** [comment]
I update the build and test instructions. Need to some one to test. If it work smoothly , You should see the sent message statistic in the webui output results

**Comment by anthonyms** [comment]
Is there a quick write up on how to set up and run the test?

**Comment by KingOfPoptart** [comment]
@artfullyContrived  https://github.com/DemandCube/NeverwinterDP/#how-to-build-neverwinterdp

**Comment by louzar** [comment]
I already test it once, I will test it again and send the errors in the log file

**Comment by KingOfPoptart** [comment]
Seems ok to me, gonna go ahead and close
