### ISSUE TITLE
Jenkins-configs - Remove entire localVMTesting folder

### ISSUE THREAD

**Issue by KingOfPoptart** [DemandCube/NeverwinterDP_Legacy#250]
This folder is now extraneous.  

Since you're working on a branch now, Peter, go ahead and remove this entire folder to help reduce the size of this repo.

**Comment by jeroldleslie** [comment]
@KinfOfPoptart removed entire localVMTesting folder https://github.com/DemandCube/Jenkins-configs/pull/6
