### ISSUE TITLE
Fix tests running on Jenkins for Demandspike

### ISSUE THREAD

**Issue by KingOfPoptart** [DemandCube/NeverwinterDP_Legacy#257]

**Comment by KingOfPoptart** [comment]
Review test failures for http://jenkinsdp.do.demandcube.com:8080/view/Auto%20Commit%20Tests/job/push_request_test_Demandspike/

And figure out how to get the tests 100% passing.

**Comment by tuan08** [comment]
Sorry , I write a wrong comment

**Comment by tuan08** [comment]
Look like I already fix this broken test yesterday night and it should be updated in the next build
