### ISSUE TITLE
Fix tests running on Jenkins for NeverwinterDP-Commons

### ISSUE THREAD

**Issue by KingOfPoptart** [DemandCube/NeverwinterDP_Legacy#258]
Check out http://jenkinsdp.do.demandcube.com:8080/view/Auto%20Commit%20Tests/job/push_request_test_NeverwinterDP-Commons/

and figure out how to get tests 100% passing

**Comment by tuan08** [comment]
I check in the fix. Next time create the issue only if you see the test broken for 3 days

**Comment by KingOfPoptart** [comment]
Reassigning this to @tuan08 , not sure why I assigned this to myself...

**Comment by tuan08** [comment]
I fix it and reasign to you. If you see it is fixed in jenkins , then you can close the issue
