### ISSUE TITLE
Fix test on Jenkins for HadoopSingleNodeCluster

### ISSUE THREAD

**Issue by smorin** [DemandCube/NeverwinterDP_Legacy#260]
http://jenkinsdp.do.demandcube.com:8080/job/HadoopSingleNodeCluster/lastFailedBuild/console

Started by user Steve Morin
[EnvInject] - Loading node environment variables.
Building remotely on slave1Jenkins (ubuntuslave swarm) in workspace /var/lib/jenkins/jenkins-slave/workspace/HadoopSingleNodeCluster
Fetching changes from the remote Git repository
Fetching upstream changes from https://github.com/DemandCube/hadoop-single-node-cluster.git
ERROR: Couldn't find any revision to build. Verify the repository and branch configuration for this job.
Finished: FAILURE

**Comment by KingOfPoptart** [comment]
Reassigning to Peter, this is his config

**Comment by jeroldleslie** [comment]
Added three new jobs for HadoopSingleNodeCluster 1. HadoopSingleNodeCluster_nightly, 2. HadoopSingleNodeCluster_pull_request_test, 3. HadoopSingleNodeCluster_push_request_test. @smorin please review it

**Comment by KingOfPoptart** [comment]
None of these tests are publishing any test results.  Is that intentional? Is there no formatted .xml output from any junit or any other kind of output?

Also the pull request test is failing:

```
Complete!
2014/08/01 09:25:21 The command [/bin/sh -c yum update -y] returned a non-zero code: 1
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```
