### ISSUE TITLE
[RingBearer] Create the RingBearer repository

### ISSUE THREAD

**Issue by tuan08** [DemandCube/NeverwinterDP_Legacy#262]
And assign the write permission for me

**Comment by smorin** [comment]
Do you think the testing framework should be an entirely new Project or
just a subcomponent of NeverwinterDP?
-Steve

On Thu, Jul 31, 2014 at 12:15 AM, Tuan Nguyen notifications@github.com
wrote:

> Assigned #262 https://github.com/DemandCube/NeverwinterDP/issues/262 to
> @smorin https://github.com/smorin.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/DemandCube/NeverwinterDP/issues/262#event-147575903.

## 

Steve Morin | Hacker, Entrepreneur, Startup Advisor
twitter.com/SteveMorin | stevemorin.com
_Live the dream start a startup. Make the world ... a better place._

**Comment by tuan08** [comment]
Yes , I can leave it in NeverwinterDP as it will be depepended on all the other projects.

**Comment by smorin** [comment]
That works, just put those pieces in their own section for
com.neverwinterdp.ringbearer

On Thu, Jul 31, 2014 at 6:39 PM, Tuan Nguyen notifications@github.com
wrote:

> Yes , I can leave it in NeverwinterDP as it will be depepended on all the
> other projects.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/DemandCube/NeverwinterDP/issues/262#issuecomment-50840473
> .

## 

Steve Morin | Hacker, Entrepreneur, Startup Advisor
twitter.com/SteveMorin | stevemorin.com
_Live the dream start a startup. Make the world ... a better place._
