### ISSUE TITLE
[NeverwinterDP] Create gradle clean build install for NeverwinterDP

### ISSUE THREAD

**Issue by tuan08** [DemandCube/NeverwinterDP_Legacy#263]
Can you create a test for NeverwinterDP as we move the current DemandSpike code to NeverwinterDP. Also could you rename push_request_test_NeverwinterDP to NeverwinterDP_push_request_test. It is easier to find the project

**Comment by KingOfPoptart** [comment]
http://jenkinsdp.do.demandcube.com:8080/view/Auto%20Commit%20Tests/job/push_request_test_NeverwinterDP/

Is that what you're looking for?

Also I won't be renaming the jobs, it keeps all the push tests together, pull tests together, etc.

**Comment by tuan08** [comment]
Yes , it is done. I will review the test to see if I can fix some exception later
