### ISSUE TITLE
[NeverwinterDP] Tuning NeverwinterDP system

### ISSUE THREAD

**Issue by tuan08** [DemandCube/NeverwinterDP_Legacy#264]
1. Create a vagrant script to launch multiple machine with different name and role
2. Develop the necessary script to launch the empty java server, deploy queuengin , sparkngin ... services on the corresponding servers and launch the services.
3. Develop the necessary script to monitor , collect and analyze the log files.
4. run the existed script test on the real cluster.
5. Analyse the performance, exceptions, 
6. tune the kafka, zookeeper properties confguration.
7. Tune the sparkngin, improve the performance , stability, acknowledge...
8. Should we implement the sparkngin client that can handle the failure and send to the other sparkngin
9. Improve log and statistic monitor
10. Shutdown the cluster system.

**Comment by tuan08** [comment]
Steve,

It will help if Peter or Anthony can crete a script that launch 3 server with the given hostname such queuengin, sparkngin... install java , and start a script that run the command java -version

**Comment by tuan08** [comment]
I need it as soon as possible.

**Comment by KingOfPoptart** [comment]
I'm assigning @jeroldleslie to this task

@jeroldleslie please coordinate with Tuan for any clarification or instructions.

For step 1 - please use vagrant flow to create and configure the machines

**Comment by jeroldleslie** [comment]
@tuan08, I need clear Idea about this task, can you please explain this task.

**Comment by tuan08** [comment]
Hi , 

I already make it clear , a script to lauch 3 servers. The hostname has to set to  queuengin, sparkngin and demandspike. Inistall a script into /etc/init.d/myscript.sh,  in myscript.sh ,  run the command java -version

**Comment by tuan08** [comment]
I will continue from your script after you finish

**Comment by smorin** [comment]
I understand what Peter means this is vague.   You obviously have a very clear idea in your head.  If you can explain in more details with and example as part of the description it would help

**Comment by jeroldleslie** [comment]
Yes, correct steve. 

Regards,
Peter Jerold Leslie
jeroldleslie@gmail.com

**Comment by tuan08** [comment]
Hi,

I really do not know how to make it more clear. You need to ignore all the instructions in the first post.  What I need is script that create 2 - 3 server instances. The server instance need to have the java application installed and a autostart script /etc/init.d/ directory. The script should simply call the command java -version

**Comment by jeroldleslie** [comment]
Tuan,

I am telling you what I am going to do now.
1. Launch 3 VM with hostname queuengin, sparkngin and demandspike.
2. Install java on each machines.
3. Install a script into /etc/init.d/myscript.sh on each machines

After that I will ask you next steps in clear.

Regards,
Peter Jerold Leslie
jeroldleslie@gmail.com

**Comment by tuan08** [comment]
Also the hostname should be set to a custom name such queuengin , sparkngin....

**Comment by tuan08** [comment]
Yes , I already say that I will continue from that or give you more instruction

**Comment by jeroldleslie** [comment]
thats great, I am moving on now.

Regards,
Peter Jerold Leslie
jeroldleslie@gmail.com

**Comment by tuan08** [comment]
The idea is you launch serveral server instances, each server will run the  queuengin ,  sparkngin , kafka .... But you will need to go deeper into our script

**Comment by jeroldleslie** [comment]
ok

Regards,
Peter Jerold Leslie
jeroldleslie@gmail.com

**Comment by jeroldleslie** [comment]
Hi tuan,
I have launched multiple VM. Steps what I did now 
1. launched multiple VM with name queuengin, sparkngin, demandspike.
2. Installed java on each VM.
2. Created neverwinterdp, with commands
     #!/usr/bin
1. Installed service init script in each VM (added service neverwinterdp in /etc/init.d/)

**Comment by tuan08** [comment]
Could you check in code and give me the instructions how to run.  In the mean time , you can follow the README.md in NeverwinterDP to build and run my code. I will give you more instruction after review

**Comment by jeroldleslie** [comment]
Please Ignore previous comment. submitted unexpectedly.

Hi tuan,
I have launched multiple VM. Steps what I did now 
1. launched multiple VM with name queuengin, sparkngin, demandspike.
2. Installed java on each VM.
3. Created neverwinterdp, with commands
#!/usr/bash
java -version
4. Added neverwinterdp into /etc/init.d/ (Installed service)
5. Started service on each VM

For this I am using vagrant-flow and DemandCubePlaybook.

What are the next steps to do?

**Comment by jeroldleslie** [comment]
unfortunately vagrant-flow is not working now on virtualmachine from today morning. due to fix in #244 it breaks virtualmachine functionality.

**Comment by tuan08** [comment]
Peter,

The next step is to build and NeverwinterDP, 
1. Try to run with the local-multi-jvm.sh script. 
2. Once you test succesfully on your local. Update the vagrant script to deloy the  release/NeverwinterDP dir to  the /opt/NeverwinterDP of each VM machine, make sure you update the permission and allow the user to read/write to the /opt/NeverwinterDP directory.
3. Create a script like local-multi-jvm.sh , instead launching the server with the hardcode server name and role,  pick the server name and role from the hostname command.
4. Lauch the script

**Comment by tuan08** [comment]
This has been partially done and need more iteration later , when the metric framework improve
