### ISSUE TITLE
Rename jobs on Jenkins

### ISSUE THREAD

**Issue by KingOfPoptart** [DemandCube/NeverwinterDP_Legacy#265]
Rename jobs so that the repo name comes first
i.e. NeverwinterDP_push_request_test, NeverwinterDP_pull_request_test

Also update the regex's in views http://jenkinsdp.do.demandcube.com:8080/view/Auto%20Pull%20Tests/ and http://jenkinsdp.do.demandcube.com:8080/view/Auto%20Commit%20Tests/ under Edit View->Use a regular expression...

**Comment by jeroldleslie** [comment]
@KingOfPoptart completed please review
