### ISSUE TITLE
HadoopSingleNodeCluster nightly is failing.

### ISSUE THREAD

**Issue by KingOfPoptart** [DemandCube/NeverwinterDP_Legacy#268]
The job is failing.  Figure out why and fix it.

http://jenkinsdp.do.demandcube.com:8080/job/HadoopSingleNodeCluster_nightly/

**Comment by jeroldleslie** [comment]
please merge https://github.com/DemandCube/hadoop-single-node-cluster/pull/20. Issue in latest docker image (fixed)
