### ISSUE TITLE
Update vagrant-centos-template with references to released images for ubuntu 12 and 13

### ISSUE THREAD

**Issue by smorin** [DemandCube/NeverwinterDP_Legacy#27]

**Comment by KingOfPoptart** [comment]
The requirements for this issue are unclear.

Do you want the VAGRANTFILE to bring up 2 VMs, do you want a separate VAGRANTFILE, or how do you want it done?

Also, shouldn't this be assigned to me?

**Comment by smorin** [comment]
Let's scratch this.  I have come up with new thoughts on how todo this now as part of Vagrant-flow
