### ISSUE TITLE
Add performance testing results to TeamWiki

### ISSUE THREAD

**Issue by KingOfPoptart** [DemandCube/NeverwinterDP_Legacy#271]
Add explanations for configurations, what units the numbers are in, and add the links under a new heading called "Performance testing" in the team wiki.

Team wiki is here - 
https://github.com/DemandCube/TeamWiki/wiki

**Comment by louzar** [comment]
wiki is updated : https://github.com/DemandCube/TeamWiki/wiki/kafka-job
