### ISSUE TITLE
Create MultiCast server

### ISSUE THREAD

**Issue by KingOfPoptart** [DemandCube/NeverwinterDP_Legacy#273]
1. Leader Election (Look at how Zookeeper does it)
2. Use Netty to make UDP client - UDP multicast server

Read in config file of where Zookeeper lives

Respond to requests with:
1.If leader - become multicast server
If not, wait to become server
2. Respond to requests with IP's of Zookeeper IP and port

**Comment by anthonyms** [comment]
You may also investigate the curator framework.
http://curator.apache.org/
It is much easier to use than accessing zookeeper directly.

**Comment by KingOfPoptart** [comment]
Pull Request is here https://github.com/DemandCube/NeverwinterDP-Commons/pull/9

Assigning to Tuan for a code review.

@smorin , could you also take a look when you get a chance.

Important files are in the packages - 
com.neverwinterdp.broadcast
com.neverwinterdp.netty.multicast
com.neverwinterdp.zookeeper.autozookeeper
