### ISSUE TITLE
[ks] - serve static files for front-end

### ISSUE THREAD

**Issue by stites** [DemandCube/NeverwinterDP_Legacy#277]
use nodejs so that we can get this up-and-running quickly

**Comment by KingOfPoptart** [comment]
You may want to consider using netty instead, since other aspects of NeverwinterDP use netty.

Use your best judgement

**Comment by stites** [comment]
@smorin and I went over architecture last week and I relayed everything to @chip2int and @lazaruslarue this weekend. I'm canning this ticket - @chip2int and I are going to look into using JMX/JMXTrans (built into kafka) to forward data to Graphite (maybe statsd, but possibly unnecessary), where we will display data via grafana (@lazaruslarue). setting this up now.

**Comment by stites** [comment]
okay actually, just unassigning this since this still has to get done : D
