### ISSUE TITLE
Scribengin - Gradleize the detect_partitions branch in preparation for merging it with master.

### ISSUE THREAD

**Issue by anthonyms** [DemandCube/NeverwinterDP_Legacy#281]
@noitcudni , @tuan08 
Any objections? Any comments?

**Comment by tuan08** [comment]
Hi,

You can merge if the build succeeds and pass all test

**Comment by anthonyms** [comment]
This adds gradle capabilities to Lih's branch in preparation for merging to master.  Merging to master will be done later. 

PR.
https://github.com/DemandCube/Scribengin/pull/7

**Comment by anthonyms** [comment]
This was merged and closed.
