### ISSUE TITLE
Scribengin - Dynamic Configuration of ScribenginApplicationMaster

### ISSUE THREAD

**Issue by anthonyms** [DemandCube/NeverwinterDP_Legacy#288]
As per email discussion with Lih

Yarn Application Master (ScribenginAM)'s buildCommandList method doesn't do a whole lot right now. Iterate through its topicMetadataMap and build a list of commands that invoke ScribeConsumer. These commands will be run inside allocated containers (See AbstractApplicationMaster).

**Comment by KingOfPoptart** [comment]
For now it works, deferring any enhancements until v2
