### ISSUE TITLE
Sparkngin Enhancements

### ISSUE THREAD

**Issue by KingOfPoptart** [DemandCube/NeverwinterDP_Legacy#291]
1. Configure to be able to run on either HTTP or HTTPS
2. Pixel server - Sparkngin able to serve a 1x1 pixel for tracking purposes

**Comment by tuan08** [comment]
Richard ,

I will create a template code and unit test for you and Peter. Hope it will help

**Comment by KingOfPoptart** [comment]
@tuan08 Please review https://github.com/DemandCube/NeverwinterDP-Commons/pull/12

**Comment by KingOfPoptart** [comment]
TODO: snoop data from HTTP request

**Comment by KingOfPoptart** [comment]
@tuan08 can you please review https://github.com/DemandCube/Sparkngin/pull/23  - I added the option to turn on the pixel server and added tests.  Shouldn't take too long to go over, just want to make sure I'm doing things right

**Comment by tuan08** [comment]
There is  a better way to do this , also I think deploy  pixel route handler to sparkngin is not a good idea. Need to talk to you

**Comment by smorin** [comment]
Richard, let's the three of us discuss this today.
-Steve
