### ISSUE TITLE
Problem building NeverwinterDP-Commons - build failed

### ISSUE THREAD

**Issue by smorin** [DemandCube/NeverwinterDP_Legacy#294]
The build is currently failing and looks like it's happening because of broadcast module

Steves-iMac:NeverwinterDP-Commons smorin$ gradle clean build install --debug 

fast forward through stack trace --->

19:41:04.013 [ERROR] [org.gradle.BuildExceptionReporter] 
19:41:04.013 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
19:41:04.013 [ERROR] [org.gradle.BuildExceptionReporter] 
19:41:04.013 [ERROR] [org.gradle.BuildExceptionReporter] \* What went wrong:
19:41:04.014 [ERROR] [org.gradle.BuildExceptionReporter] Could not resolve all dependencies for configuration ':broadcastserver:testCompile'.
19:41:04.014 [ERROR] [org.gradle.BuildExceptionReporter] > Could not find com.neverwinterdp:commons.zookeeper:1.0-SNAPSHOT.
19:41:04.014 [ERROR] [org.gradle.BuildExceptionReporter]   Searched in the following locations:
19:41:04.014 [ERROR] [org.gradle.BuildExceptionReporter]       file:/Users/smorin/.m2/repository/com/neverwinterdp/commons.zookeeper/1.0-SNAPSHOT/maven-metadata.xml
19:41:04.014 [ERROR] [org.gradle.BuildExceptionReporter]       file:/Users/smorin/.m2/repository/com/neverwinterdp/commons.zookeeper/1.0-SNAPSHOT/commons.zookeeper-1.0-SNAPSHOT.pom
19:41:04.014 [ERROR] [org.gradle.BuildExceptionReporter]       file:/Users/smorin/.m2/repository/com/neverwinterdp/commons.zookeeper/1.0-SNAPSHOT/commons.zookeeper-1.0-SNAPSHOT-tests.jar
19:41:04.014 [ERROR] [org.gradle.BuildExceptionReporter]       http://repo1.maven.org/maven2/com/neverwinterdp/commons.zookeeper/1.0-SNAPSHOT/maven-metadata.xml
19:41:04.015 [ERROR] [org.gradle.BuildExceptionReporter]       http://repo1.maven.org/maven2/com/neverwinterdp/commons.zookeeper/1.0-SNAPSHOT/commons.zookeeper-1.0-SNAPSHOT.pom
19:41:04.015 [ERROR] [org.gradle.BuildExceptionReporter]       http://repo1.maven.org/maven2/com/neverwinterdp/commons.zookeeper/1.0-SNAPSHOT/commons.zookeeper-1.0-SNAPSHOT-tests.jar
19:41:04.015 [ERROR] [org.gradle.BuildExceptionReporter]   Required by:
19:41:04.015 [ERROR] [org.gradle.BuildExceptionReporter]       com.neverwinterdp:broadcastserver:1.0-SNAPSHOT
19:41:04.015 [ERROR] [org.gradle.BuildExceptionReporter] 
19:41:04.015 [ERROR] [org.gradle.BuildExceptionReporter] \* Try:
19:41:04.016 [ERROR] [org.gradle.BuildExceptionReporter] Run with --stacktrace option to get the stack trace. 
19:41:04.016 [LIFECYCLE] [org.gradle.BuildResultLogger] 
19:41:04.016 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED
19:41:04.016 [LIFECYCLE] [org.gradle.BuildResultLogger] 
19:41:04.016 [LIFECYCLE] [org.gradle.BuildResultLogger] Total time: 3.047 secs

**Comment by tuan08** [comment]
Which branch are you using , It seems that I do not have this problem

**Comment by smorin** [comment]
master

I checked and did a fresh pull request on every project.

I also checked for rogue gradle processes.

On Tue, Aug 19, 2014 at 7:50 PM, Tuan Nguyen notifications@github.com
wrote:

> Which branch are you using , It seems that I do not have this problem
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/DemandCube/NeverwinterDP/issues/294#issuecomment-52728154
> .

## 

Steve Morin | Hacker, Entrepreneur, Startup Advisor
twitter.com/SteveMorin | stevemorin.com
_Live the dream start a startup. Make the world ... a better place._

**Comment by KingOfPoptart** [comment]
I saw this issue when rebuilding Jenkins yesterday.  I think there's a circular dependency on the zookeeper snapshot somewhere.

**Comment by tuan08** [comment]
Actually  broadcastserver is depended  on the zookeeper tests and and zookeeper test is not built and installed

**Comment by tuan08** [comment]
OK , I fix the build config and check in the fix

**Comment by smorin** [comment]
Should the Jenkins test reflect this? Think when I checked it passed

**Comment by KingOfPoptart** [comment]
Well once you have the snapshot installed, the test will pass.  

I guess the "gradle clean" task doesn't uninstall the snapshot's its depending on, so once it _does_ get built, it doesn't disappear.

**Comment by tuan08** [comment]
Hi , 

this is the dependency problem. The new configuration will make sure that broadcastserver test depend on the zookeeper test output

**Comment by tuan08** [comment]
check my fix

**Comment by smorin** [comment]
So will rebuilding replace the snapshot? Or is there a way to remove the snapshot?

**Comment by tuan08** [comment]
It is the dependency configuration bug, not thing to do with the snapshot. The new configuration make sure that broadcast depends on  zookeeper output. The old configuration make broadcastserver depends on the zookeeper project in .m2 repository, which is not deployed yet in the compile and test phase
