### ISSUE TITLE
Create neverwinterdp-cluster.sh to manage neverwinterdp cluster

### ISSUE THREAD

**Issue by tuan08** [DemandCube/NeverwinterDP_Legacy#296]
Create a template script to:

initvm: configure and launch the vm machines 
setup: install jdk and other requirements
build:  build neverwinterdp projects and its related projects
deploy: deploy the neverwinterdp to vm machines
many other sub command such status, up, shutdown, suspend, resume, log to manage the cluster

Peter, can you commit the template script and put the link to this script

**Comment by jeroldleslie** [comment]
tuan,
script is commited in https://github.com/jeroldleslie/NeverwinterDP/tree/master/vagrant-flow

**Comment by jeroldleslie** [comment]
You can find cluster hosts file on the path /opt/NeverwinterDP/hosts of all launched VM's
it will be in the format
generic=192.168.1.2
elasticsearch=192.168.1.3
