### ISSUE TITLE
Scribengin - Use commons.cluster to create testing kafka/zookeeper servers for unit tests

### ISSUE THREAD

**Issue by KingOfPoptart** [DemandCube/NeverwinterDP_Legacy#297]
This is to avoid code divergence and promote code reuse across the board.

**Comment by smorin** [comment]
Makes sense

**Comment by anthonyms** [comment]
@tuan08 
Please modify the ZookeeperClusterBuilder to allow user specify the zkPort.  Default is of course 2181 but I need to run it on a different port for testing. 

I was previously using 
https://curator.apache.org/apidocs/org/apache/curator/test/TestingServer.html 
which allowed me to specify a different port.

**Comment by tuan08** [comment]
There is a ScribenginClusterUnitTest , did you try to run it and change the port? All the -Pzk:  and -P:kafka  are the configuration of zookeeper and kafka
