### ISSUE TITLE
Install Kafka web console and create ansible script

### ISSUE THREAD

**Issue by smorin** [DemandCube/NeverwinterDP_Legacy#30]
It will be to install and run https://github.com/claudemamo/kafka-web-console using our centos 6.5 vagrant image on the Sparknin-developer-setup, machine: sparkngin2

Once you have it running with instructions on how to start and access it.

Part 2 will be to create the ansible scripts to get it installed.  This is more important and something I'll need much sooner.

**Comment by smorin** [comment]
@mehikmat review the instructions that I sent you from Anthony on how to set it up

**Comment by mehikmat** [comment]
I saw the attachment containing the setup instructions. It's good.
And I believe that we just need to translate them into ansible to make ansible script for installing Kafka-web-console.
Overall is good and very cool documentation.

**Comment by mehikmat** [comment]
Ansible script development completed.

**Comment by smorin** [comment]
This is great
