### ISSUE TITLE
vagrant-flow: implement command init-flow

### ISSUE THREAD

**Issue by smorin** [DemandCube/NeverwinterDP_Legacy#31]
vagrant init-flow
"Is meant to create a stub Vagrantfile in the current directory that allows machine to talk to each other by default.  Will name the individual machines.  It will also reference the appropriate demandcube machine image type for each machine referenced"

```
vagrant init-flow # print usage
vagrant init-flow hostname1[:type] [hostname2[:type]] [....]  # creates Vagrantfile  
```

default type=centos-64
types=[centos-64,centos-65,ubuntu-12,ubuntu-13]

Example:

```
vagrant init-flow sparkngin sparkngin2:ubuntu-12 jenkins1:centos-65
```

**Comment by KingOfPoptart** [comment]
Fixed
https://github.com/DemandCube/vagrant-flow/pull/5
