### ISSUE TITLE
Extend vagrant flow

### ISSUE THREAD

**Issue by tuan08** [DemandCube/NeverwinterDP_Legacy#315]
Need to extend the vagrant flow  so it can be used in the vagrant script as https://github.com/smdahlen/vagrant-hostmanager. 

Ideal features to support:
1.  select the ip base on the ip pattern for each provider or  parameters. Check vagrant-hostmanager sample to see how its pick the ip for each vm and provider.
2.  Keep an ip list with the hostname, update /etc/hosts with a define provision or shell provision. Ideally , populate the ip list so the shell provision or other provision script can access and generate other configuration with the script.
3. Update /etc/hosts when all VMs are launched. Try to figure out how to use shell script or some other script to do this.

You should:

ssh neverwinterdp@NevewinterDP1
cd projects/DemandCube/NeverwinterDP
gradle clean vagrant 
cd  build/vagrant

Check VagrantScript file and try to integrate your plugin with this script file.

**Comment by tuan08** [comment]
You can also run locally , just need to ssh to the machine , copy the projects/DemandCube/apps dir to your local. This directory contains the jdk rpm and Yourkit to install on the vm.  the apps dir must be in the same level with the NeverwinterDP directory. the apps dir is too big to commit to github

**Comment by KingOfPoptart** [comment]
Band-aid solution:
You'll need to update vagrant-flow:

```
vagrant plugin install vagrant-flow
```

Create a file called multiinitconfig.yml.  For this case, the file will only need to contain the digital ocean token:

```
---
:digitalOceanToken: digitalOceanTokenGoeshere
```

Run:

```
vagrant up --provider=digital_ocean
vagrant flow hostfile -d

#This will run the command on all machines in your Vagrantfile
vagrant flow multicommand -c "command to run"
```

If you want to run commands on only select machines:

```
vagrant flow multicommand -c "command to run" -f machineName1,machineName2
```

**Comment by KingOfPoptart** [comment]
@tuan08 

New fix: No longer need to have multiinitconfig.yml.  Go ahead and delete that file and run this to update:

```
vagrant plugin install vagrant-flow
vagrant flow installdotoken -t  [digitaloceantoken]
```

Now you'll be able to connect with the digitalocean machines no problem.

**Comment by KingOfPoptart** [comment]
Also it is possible to run shell commands at the end of your vagrant script.  So your vagrant script could look like this  (Take a look at the end of it)  Every time you run "vagrant up" It will execute the two commands. :

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  Vagrant.require_version ">= 1.4.3"

  config.vm.define :fulldefaults do | fulldefaults |    
    fulldefaults.vm.box = "demandcube/centos-65_x86_64-VB-4.3.8"

    # Create a private network
    fulldefaults.vm.network :private_network, ip: "192.168.1.2", virtualbox__intnet: "neverwinterDP"
    fulldefaults.vm.hostname = "fulldefaults"

    fulldefaults.vm.synced_folder  ".", "/vagrant", disabled: true

    #digitalOcean provider
    fulldefaults.vm.provider :digital_ocean do |provider, override|
      override.ssh.private_key_path = '/Users/rcduar/x/teamaccess'
      provider.token  = 'blahblahblahblahblah'
      provider.region = 'sfo1'
      provider.image  = 'CentOS 6.5 x64'
      provider.size   = '512MB'
    end

    #VirtualBox provider
    fulldefaults.vm.provider :virtualbox do |vb|
      vb.name = "fulldefaults"
      vb.customize ["modifyvm", :id, "--memory", "512"]
      # vb.customize ["modifyvm", :id, "--cpus", "2"]
    end

  end
end

puts `vagrant flow hostfile -d`
puts `vagrant flow multicommand -c "command to run"`

```

**Comment by smorin** [comment]
Have both of you been able to discuss the changes and feature you want in
this Richard and Tuan?
