### ISSUE TITLE
DemandSpike for Sparkngin

### ISSUE THREAD

**Issue by louzar** [DemandCube/NeverwinterDP_Legacy#316]

**Comment by louzar** [comment]
- Understand the existing code of Demandspike and ringbearer
- Implement Shell Script parser 
- Implement Main Class with Jcommander
- Implement SpikeSchedule, HttpProtocol, DataGenerator, SpikeWorker

**Comment by louzar** [comment]
Childrens Tickets
https://github.com/DemandCube/NeverwinterDP/issues/317
https://github.com/DemandCube/NeverwinterDP/issues/318
https://github.com/DemandCube/NeverwinterDP/issues/319
https://github.com/DemandCube/NeverwinterDP/issues/320

**Comment by jeroldleslie** [comment]
assigned to @louzar
