### ISSUE TITLE
vagrant-flow: implement command hostfile-remote

### ISSUE THREAD

**Issue by smorin** [DemandCube/NeverwinterDP_Legacy#33]
The goal is to be able to update host files /etc/hosts on each vm so they can talk to each other.

This should research a solution based on how other people solved it including

Host file techniques
https://github.com/adrienthebo/vagrant-auto_network
https://github.com/adrienthebo/vagrant-hosts
https://github.com/cogitatio/vagrant-hostsupdater
https://github.com/smdahlen/vagrant-hostmanager
https://github.com/mosaicxm/vagrant-hostmaster

**Comment by KingOfPoptart** [comment]
DemandCube/vagrant-flow#6 submitted for review

**Comment by KingOfPoptart** [comment]
Merged.
