### ISSUE TITLE
Sparkngin - Able to talk to multiple endpoints

### ISSUE THREAD

**Issue by KingOfPoptart** [DemandCube/NeverwinterDP_Legacy#336]
Multiple endpoints = 1 kafka cluster, but can handle multiple topics

**Comment by KingOfPoptart** [comment]
Parent is https://github.com/DemandCube/NeverwinterDP/issues/335

**Comment by tuan08** [comment]
TODO:

Implement sparkngin topic endpoint for ex  http://localhost:port/message/json/:topicName  and the message will be forwarded to  kafka topicName
