### ISSUE TITLE
Sparkngin - GET and POST methods run concurrently

### ISSUE THREAD

**Issue by KingOfPoptart** [DemandCube/NeverwinterDP_Legacy#337]
GET request = gets pixel
POST request = sends full data
Command line configurable to be able to do GET, POST, or GET and POST at the same time

Parent is https://github.com/DemandCube/NeverwinterDP/issues/335

**Comment by tuan08** [comment]
This is done. Basically each endpoint accept both post and get method. 
1. With the GET method you need to pass the message data via http://host:port/endpoint?data=data. You need to make sure that the data size is less than 2kb or according to the server and client config.
2. With the POST method , you need to pass the message data in the request body.

**Comment by tuan08** [comment]
This requirement is misunderstood. The GET pixel is another requirement and it is under the tracking service endpoint implementation. When a client make a request to the tracking service end point, a transparent pixel will be returned to the client and the request header will be converted to the message and send to the sparkngin.
