### ISSUE TITLE
Sparkngin - Configuring which data to store from a GET request on Pixel server

### ISSUE THREAD

**Issue by KingOfPoptart** [DemandCube/NeverwinterDP_Legacy#338]
GET (pixel)
- Configure which headers to forward to Kafka
- Should be an “ALL” headers mode
- Which headers to store is configured by a properties file
- Default behavior/properties file is missing -  is to get all headers and forward to kafka

Parent is https://github.com/DemandCube/NeverwinterDP/issues/335

**Comment by tuan08** [comment]
DONE

**Comment by smorin** [comment]
A sample of the configuration needs to be proposed and reviewed by the team.

**Comment by tuan08** [comment]
Hi ,

Basically, the sparkngin have few main parameters such data-dir, forwarder and several plugin for example endpoint handler, different forwarder implementation. Each plugin itself require a set of parameters. So I have a huge properties file that contains all the configuration. A plugin component can access its parameters by getting the set of the parameters with the key prefix , for ex  mainCofig.getConfigFor("tracking.site"), mainCofig.getConfigFor("forwardre.nulldev") ... This design allow you to have a default and documented configuration properties file and you need to override only the parameter you want  to  update. The problem with the design is a dynamic and highly customizable code will require a lot of the plugin component with many different parameters. To maintain, document all the parameters will cost a lot of time. A developer will need a lot of time to learn too. But I found this problem happen to all the configuration frameworks.

Here is a sample of configuration that you can override the default configuration via command line argument.

runServer \
    --data-dir $APP_DIR/data --forwarder nulldev \
    --sparkngin:tracking.site.log-topic=site.log \
    --sparkngin:tracking.site.extract-headers=Host.\* \
    --sparkngin:forwarder.nulldev.dump=true \
    --kafka:metadata.broker.list=127.0.0.1:9092
