### ISSUE TITLE
Sparkngin - configuring how to send data through POST in Sparkngin

### ISSUE THREAD

**Issue by KingOfPoptart** [DemandCube/NeverwinterDP_Legacy#339]
for POST requests to Sparkngin
The ability to configure whether -
1. Send the binary data from the post only
2. Send a json message with a headers section and body field (body is contents of the post)
3 .[Nice to have] The ability to add a pluggable validator of the request - this can wait until Beta

Parent is - https://github.com/DemandCube/NeverwinterDP/issues/335

**Comment by tuan08** [comment]
This has been implemented with the design:
1. The sparkngin http connector can handle different endpoint or path. Each path can accept both POST and GET method for ex:  http:/localhost:post/message/json accept the json data, http:/localhost:post/message/jbinary  accept the java serializable message object.
2. json and java binary endpoint have been implemented
