### ISSUE TITLE
vagrant-flow: implement command flow

### ISSUE THREAD

**Issue by smorin** [DemandCube/NeverwinterDP_Legacy#34]

**Comment by KingOfPoptart** [comment]
Fixed I think?
https://github.com/DemandCube/vagrant-flow/pull/5

vagrant-flow can support multiple commands now.  Is that what the purpose of this task was?

**Comment by smorin** [comment]
Richard what are your thoughts on implementing the flow sub-command?

**Comment by KingOfPoptart** [comment]
I haven't had a chance to play around to see if I can implement the uber-flow command that runs all 4 steps of vagrant flow yet.  I'll let you know when I have a chance.  As of now, the flow works fine so I would consider it a lower priority than coming up with the testing strategy for installation tests.

**Comment by smorin** [comment]
Makes sense to me
