### ISSUE TITLE
Yara - complete Yara distributed metrics framework

### ISSUE THREAD

**Issue by KingOfPoptart** [DemandCube/NeverwinterDP_Legacy#349]
Parent is https://github.com/DemandCube/NeverwinterDP/issues/348

**Comment by tuan08** [comment]
TODO:
1. Refractor the sparkngin persistent buffer  to make it reusable and reuse the buffer framework in  metric client framework and elasticsearch client framework.
2. Implement the metric deamon server using netty thrift  protocol.
3. Implement metric client that use the persistent buffer to buffer metric log and send the metric log to the deamon server periodically
