### ISSUE TITLE
Implement the log4j elasticsearch appender

### ISSUE THREAD

**Issue by tuan08** [DemandCube/NeverwinterDP_Legacy#351]
Implement the log4j elasticsearch appender that uses the persistent buffer and implement a basic webui to show the log with our webui framework

**Comment by smorin** [comment]
How is this supposed to work and why?

Would it be better just to log to Kafka and use scribengin to load elastic search?

**Comment by tuan08** [comment]
Hi,

Log4j has a log appender plugin that allow you to customize different appender to output the data to different destination for ex console appender , file appender , jms appender. I already wrote an elasticsearch appender to output the log to elasticsearch server and it work properly. The problem is when we have a bunch of servers to launch and output the log, the elasticsearch appender client can be started and output the data before the elasticsearch is started and it causes the data lost and exception. So I need to use the persistent buffer to avoid the data lost , also the buffer allow you to batch the message that will increase the performance significantly.

**Comment by tuan08** [comment]
Sorry , I think I make mistake here , my current appender send the data to sparkngin , not elasticsearch. But my issue is it has to integrate with a persistent buffer since there is a network failure problem , sparkngin is dead or not launched yet
