### ISSUE TITLE
Scribengin - Figure out cleanStart algorithm

### ISSUE THREAD

**Issue by KingOfPoptart** [DemandCube/NeverwinterDP_Legacy#353]
From Lih's code review:
Clean start might require more than just setting the offsets to 0. In fact, setting it to zero will most likely not work, as the beginning of the offset may not start from zero. I guess the real question is what do you mean by cleanStart? Start from the very very beginning and ignore the log? If so, there's is option to get the offset for HEAD in kafka. Also, I'm not sure what we should do with the old content of the log in this case.

Clean Start option needs to be figured out in ScribeConsumer.  Need to decide what to do with the commit log and what offset to read from

**Comment by KingOfPoptart** [comment]
Parent is #340

**Comment by anthonyms** [comment]
@KingOfPoptart 

From #342 

> If start a scribengin worker thread - The worker must throw an error if reading from offset zero >UNLESS the clean start parameter is set (human-proofing)

Do we really need to exit if reading from the earliest offset?
This would mean that all first time runs must provide the --clean_start  param

**Comment by KingOfPoptart** [comment]
That is correct.  Steve called this feature "human-proofing" it.  

In most cases, Scribengin should be a "long lived" process, so it should almost never be reading from the beginning offset.  Scribengin should be recovering from some sort of failure upon starting up in most cases, so if it ever finds itself reading from the beginning when it hasn't been explicitly told to do so, it should throw an error.
