### ISSUE TITLE
Scribengin Remove --command and --container_cnt options

### ISSUE THREAD

**Issue by KingOfPoptart** [DemandCube/NeverwinterDP_Legacy#354]
When running Scribengin, 

```
/usr/lib/hadoop/bin/hadoop jar scribengin-1.0-SNAPSHOT.jar --container_mem 300 --am_mem 300 --container_cnt 1  --hdfsjar /scribengin-1.0-SNAPSHOT.jar --app_name foobar --command echo --am_class_name "com.neverwinterdp.scribengin.ScribenginAM" --topic scribe --kafka_seed_brokers 10.0.2.15:9092
```

--command doesn't do anything - remove it
--container_cnt is useless as well since we should be creating one container per topic, so go ahead and remove it.  the ScribeMaster class will be in charge of how many yarn threads to have.

Parent is #340

**Comment by anthonyms** [comment]
> the ScribeMaster class will be in charge of how many yarn threads to have.

Thats a separate issue or bundled into this one?

**Comment by KingOfPoptart** [comment]
That is a separate issue.  I'm working on that

**Comment by noitcudni** [comment]
Let's do one container per kafka topic. That's why it doesn't really make
sense to dictate the number of containers to be spun up at the common line.
Just wanted to give some context.

Lih

**Comment by smorin** [comment]
Lih do you mean one container per Kafka topic and partition?

**Comment by noitcudni** [comment]
yes, sorry. i meant one container per topic per partition.
