### ISSUE TITLE
Scribengin - Update SupportClusterBuilder to use Lih's KafkaFixture to launch kafka in a more reliable way

### ISSUE THREAD

**Issue by KingOfPoptart** [DemandCube/NeverwinterDP_Legacy#356]
Update - 
https://github.com/DemandCube/Scribengin/blob/master/src/test/java/com/neverwinterdp/scribengin/clusterBuilder/SupportClusterBuilder.java

The current method of launching kafka using the cluster framework is unreliable.  Update the SupportClusterBuilder by removing the launching of kafka and change it to support Lih's kafkaFixture framework

The methodology for using supportClusterBuilder should remain the same:

```
supportClusterBuilder = new SupportClusterBuilder();
supportClusterBuilder.install();
......
supportClusterBuilder.destroy();
```

**Comment by KingOfPoptart** [comment]
Parent is #340

**Comment by anthonyms** [comment]
@KingOfPoptart 
For consistency and symmetry I intend to have the uninstall method be the converse of install and remove the destroy method.
Thus

```
supportClusterBuilder = new SupportClusterBuilder();
supportClusterBuilder.install();
......
supportClusterBuilder.uninstall();
```

Did you have a different use case in mind for the uninstall method?

**Comment by KingOfPoptart** [comment]
No, that should be fine
