### ISSUE TITLE
[Scribengin] Fix docker readme

### ISSUE THREAD

**Issue by KingOfPoptart** [DemandCube/NeverwinterDP_Legacy#465]
-Remove old 'running Scribengin' section
-Add how to compile dependencies from NeverwinterDP-Commons and Queuengin
-Specify which version of Gradle to use, or replace "gradle" with ./gradlew or ../gradlew in the commands

**Comment by tuan08** [comment]
People should know how to check out code, project build with gradle. I do not have the time to upgrade the gradle version for now
