### ISSUE TITLE
[Scribengin] Document all the commands that exist, and keep that document up to date

### ISSUE THREAD

**Issue by KingOfPoptart** [DemandCube/NeverwinterDP_Legacy#470]
The Scribengin shell has many commands.  Currently, its difficult to keep track of them all as they are in several different files in multiple packages.

Documentation should include:
- List of commands
- List of subcommands
- What all the commands/subcommands do
- What class and package the command lives in - i.e. "dataflow" commands live in com.neverwinterdp.scribengin.client.shell.DataflowCommand

This documentation needs to be updated whenever a command is added or changed.

Create a help or usage shell command, that should should loop through the available command in the shell , print out the description and option

**Comment by tuan08** [comment]
You can assign this task to some one if he interest how to create a shell command

**Comment by tuan08** [comment]
Create a help or usage shell command, that should should loop through the available command in the shell , print out the description and option

**Comment by KingOfPoptart** [comment]
Documenting your own code is part of your responsibilities, @tuan08

**Comment by tuan08** [comment]
It is not document the code. I ask to write a help command to print out the description of the other command and I think some one can work on this instead of me

**Comment by anthonyms** [comment]
@KingOfPoptart If theres no problem I can take this up.

First step is to add a help command that prints out all commands.
