### ISSUE TITLE
[Scribengin] Add command to cluster.sh to start Kafka

### ISSUE THREAD

**Issue by KingOfPoptart** [DemandCube/NeverwinterDP_Legacy#476]
./cluster.sh start --clean --with-kafka

**Comment by tuan08** [comment]
I think Peter or Richard should work on this , not Anthony for now

**Comment by KingOfPoptart** [comment]
I'm ok with that if @jeroldleslie wants to take this task.  @jeroldleslie please reassign this to yourself if you want to take it

**Comment by jeroldleslie** [comment]
ok @KingOfPoptart I will take this ticket with me.

**Comment by tuan08** [comment]
Actually it is not possible to specify the number kafka node or zookeeper node. If you want to do this , you have to do with the docker.sh 

You can only have /cluster.sh start --clean --with-kafka

Another option is to have docker.sh that can create a number of kafka instances, and the cluster.sh start a number of kafka instances , but not more than the number of kafka container that create by the docker.sh

**Comment by jeroldleslie** [comment]
Yes @tuan08 for now it is not possible to start with specific number of kafka nodes. so we go with your idea. /cluster.sh start --clean --with-kafka
