### ISSUE TITLE
cluster.sh enhancement

### ISSUE THREAD

**Issue by tuan08** [DemandCube/NeverwinterDP_Legacy#478]
1. add ./cluster.sh clean, it should call hadoop_clean, kafka_clean, zookeeper_clean
2. add ./cluster kafka --kill-node hostname, same for zookeeper
3. add ./cluster hadoop --kill-data-node hostname
4. add ./cluster hadoop --kill-yarn-node hostname

When you finish 2, ask me to review before continue

**Comment by jeroldleslie** [comment]
@tuan08 it seems 1. is already there in ./cluster.sh. Commited code for 2,3,4. PR created. Please review it. https://github.com/DemandCube/Scribengin/pull/76
