### ISSUE TITLE
Vagrant 1.5 public box images for demandcube centos

### ISSUE THREAD

**Issue by smorin** [DemandCube/NeverwinterDP_Legacy#48]
centos-64_x86_64-VB-4.3.8
centos-65_x86_64-VB-4.3.8

**Comment by smorin** [comment]
Believe Richard already solved this one

**Comment by KingOfPoptart** [comment]
You can find info on our public boxes here:
https://vagrantcloud.com/search?utf8=%E2%9C%93&sort=&provider=&q=demandcube
