### ISSUE TITLE
Make number of zookeeper, kafka, hadoop worker customizable

### ISSUE THREAD

**Issue by tuan08** [DemandCube/NeverwinterDP_Legacy#482]
In the docker.sh allow the command:

./docker.sh container run --zk-server=1 --kafka-server=3 --hadoo-worker=3

If the option is not specified, then use the current default number

**Comment by jeroldleslie** [comment]
functionality added and committed in branch issue482. PR created https://github.com/DemandCube/Scribengin/pull/78
