### ISSUE TITLE
Vagrant 1.5 public box images for demandcube ubuntu

### ISSUE THREAD

**Issue by smorin** [DemandCube/NeverwinterDP_Legacy#49]
ubuntu-12_x86_64-VB-4.3.8
ubuntu-13_x86_64-VB-4.3.8

**Comment by smorin** [comment]
Believe Richard already solved this one

**Comment by KingOfPoptart** [comment]
I haven't added any Ubuntu boxes yet, this is still open

**Comment by KingOfPoptart** [comment]
Who's working on the Ubuntu images? Maybe they should be assigned this to give someone else experience in how vagrantcloud works? (This task should take like 10 minutes)

**Comment by smorin** [comment]
Makes sense
-Steve

On Mon, Apr 7, 2014 at 9:11 AM, Richard Duarte notifications@github.comwrote:

> Who's working on the Ubuntu images? Maybe they should be assigned this to
> give someone else experience in how vagrantcloud works? (This task should
> take like 10 minutes)
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/DemandCube/NeverwinterDP/issues/49#issuecomment-39750116
> .

## 

Steve Morin | Hacker, Entrepreneur, Startup Advisor
twitter.com/SteveMorin | stevemorin.com
_Live the dream start a startup. Make the world ... a better place._

**Comment by louzar** [comment]
I didn't found boxes under https://github.com/DemandCube/vagrant-ubuntu
like cents os have : https://github.com/DemandCube/vagrant-centos/releases

**Comment by smorin** [comment]
@pieteradejong how is vagrant-ubuntu?

**Comment by KingOfPoptart** [comment]
@pieteradejong This task needs to be done.  We are working on setting up the Jenkins slaves and we are now being held back by this task.

**Comment by KingOfPoptart** [comment]
@smorin I've done the work and created a .box file for ubuntu following the directions in vagrant-ubuntu.  I tried to push and create a release, but I don't have permissions for that in vagrant-ubuntu.

**Comment by KingOfPoptart** [comment]
I've created https://vagrantcloud.com/demandcube/ubuntu-12_x86_64-VB-4.3.8

I'm going to go ahead and close this - if we really need ubuntu 13 we can open a new issue.
