### ISSUE TITLE
[Scribengin] Integrate update_hosts.sh into docker.sh deployment - add update-hosts command and update README

### ISSUE THREAD

**Issue by KingOfPoptart** [DemandCube/NeverwinterDP_Legacy#494]
Automatically update /etc/hosts with IP's from docker images
Update the README to show new steps

**Comment by tuan08** [comment]
Yeah , it is good to have. The main problem is to  update the /etc/hosts file , you need to have the root permission. So I am not sure it is doable.

**Comment by KingOfPoptart** [comment]
The script will have to run as sudo.  To edit /etc/hosts you need to have root permission anyways - the reason for this script is to help with automation tasks, especially on jenkins (just need to enable passwordless sudo).

**Comment by tuan08** [comment]
I don't think to run as sudo is a good idea , since all the created file will belong to the root user.  Probably we should use sudo to edit the /etc/hosts file only and prompt the password for the root permission

**Comment by tuan08** [comment]
Use sudo to modify /etc/hosts only,  if the user does not have the permission , he will need to enter the password. One way to avoid the problem is to add the permission for your account into /etc/sudoers

**Comment by KingOfPoptart** [comment]
the plan is to make this its own script that only does one thing - so it'll be the only task that gets run as sudo.

Example flow:

```
cd pathTo/Scribengin/V2/docker/scribengin/
./scribengin.sh build
./docker.sh image clean
./docker.sh image build
./docker.sh container clean
./docker.sh container run
sudo ./update_hosts.sh
ssh neverwinterdp@hadoop-master
```

**Comment by KingOfPoptart** [comment]
@jeroldleslie 

New plan - 
add update-hosts as a command to docker.sh

Example flow:

```
cd pathTo/Scribengin/V2/docker/scribengin/
./scribengin.sh build
./docker.sh image clean
./docker.sh image build
./docker.sh container clean
./docker.sh container run

#Here's where you'll be adding functionality
sudo ./docker.sh update-hosts

ssh neverwinterdp@hadoop-master
```

**Comment by jeroldleslie** [comment]
It was completed. PR in https://github.com/DemandCube/Scribengin/pull/86
