### ISSUE TITLE
Configure zookeeper

### ISSUE THREAD

**Issue by tuan08** [DemandCube/NeverwinterDP_Legacy#495]
Check the zookeeper and kafka document to see how to configure zookeeper cluster correctly.  Update docker post-install

**Comment by tuan08** [comment]
check http://zookeeper.apache.org/doc/r3.3.3/zookeeperAdmin.html#sc_zkMulitServerSetup
you need to configure zookeeper correctly and test.  use cluster.sh sync to update the configuration and test

**Comment by jeroldleslie** [comment]
ok. tuan. I created configuration.sh when zookeeper starts. Cluster configurations are done there. let me check it when I am working on this ticket.

**Comment by jeroldleslie** [comment]
https://github.com/DemandCube/Scribengin/blob/master/V2/docker/scribengin/bootstrap/post-install/zookeeper/bin/configure.sh file will make zookeeper cluster env.
