### ISSUE TITLE
[Scribengin] KafkaStabilityCheckTool - Support passing different configurations into Kafka

### ISSUE THREAD

**Issue by KingOfPoptart** [DemandCube/NeverwinterDP_Legacy#499]
Should be different configuration templates, selectable on command line

**Comment by jeroldleslie** [comment]
@tuan08 can you please add more clarity on this

**Comment by tuan08** [comment]
1. Leave the kafka server config template file in  /opt/kafka/config. You should place it correctly in  post-install. 
2. update the configure.sh to allow take in the template name. Some thing like  configure.sh --config-name=default  that should be converted to /opt/kafka/config/default.properties
3. Allow to start kafka with the command cluster.sh kafka start  --clean --with-zookeeper -config-name=default or some other name that match a properties file
