### ISSUE TITLE
[Scribengin] Add unit test for the Kafka Producer

### ISSUE THREAD

**Issue by tuan08** [DemandCube/NeverwinterDP_Legacy#504]
1. List all the possible failure scenario for the kafka producer. For ex:
   shutdown the partition leader while another process sending the messages continuously
   Add new kafka broker , rebalance , reassign the leader .....
2. Write the test for those cases
3. Verify with AckKafkaWriter to make sure our writer can fix those problems

**Comment by tuan08** [comment]
Let me know your list of scenario before you work on

**Comment by tuan08** [comment]
A specific scenario need to test is:
1.  send the messages
2. Add a new kafka node
3. rebalance the topic

**Comment by tuan08** [comment]
Anthony , you can start working on this task now

**Comment by anthonyms** [comment]
Ok.
I intend to start with the following Scenarios.

Scenario 1.
Start writer in a separate thread. Write 10000 ints from 0 to 9999.
While writing, kill leader, then immediately kill newly elected leader.

Setup config
replication factor = 3,
partitions = 1.

Expected 
10000 messages read.
Messages Read include all ints from 0 to 9999. i.e no losses 

Scenario 2
Start writer in separate thread, write 10000 ints from 0 to 9999.
While writing, kill all brokers then restart them immediately. 

Setup config
replication factor = 3
partitions = 1.

Expected 
10000 messages read.
Messages Read include all ints from 0 to 9999. i.e no losses

**Comment by tuan08** [comment]
The identified problem is your producer connect to a given  broker(leader). It will cause the message lost  if the leader is killed or change and your producer continue to send the data to a death or backup broker. We already identify that if the leader is killed and the producer (client) will loose the data.

In the Steve case (rebalance the topic) wich may trigger that  the leader change (remember that the leader is moved to another machine to for the balancing reason), so the leader become a backup and it may still response and handle the client. Steve say that we loose the message in this case too.

Your scenario 1 is not different from the current test we discover and your scenario 2 is obvious that your producer will loose the data since there is no  leader to handle

**Comment by anthonyms** [comment]
How I understand AckKafkaWriter, 
We create an instance by providing a list of kafka brokers (bootstrap.servers). 
With aks=all, all brokers are always up to date. 
When we kill leader, kafka elects a new leader, AckKafkaWriter _should_ continue writing to new leader, No messages should be lost. 

The test scenarios expect AckKafkaWriter's retry mechanism to handle change of leadership.

Test scenario 2 tests AckKafkaWriters buffering messages before retrying. 
Thus if brokers are down for a short period of time, AckKafkaWriter sleep before retry should enable us to not lose any messages.

**Comment by tuan08** [comment]
What is the goal ??? The goal is to find out the original kafka producer problem ,  not my ack kafka writer problem. A cluster design should always have a member to handle the request, if not it is not a reliable design. That is why you do not have to test the case all the server down.

The producer properties you find is documented by the kafka document.

With aks=all, all brokers are always up to date
=> I do not think ack=all mean the way you understand. all mean all the replicas broker , not all broker. But the document do not mention how it will handle when a replia broker is down. That is your job to find out as. The document say one thing , but the code , behavior may not work the way it document. If the ack=all work , then we do not see the messages lost case

**Comment by tuan08** [comment]
My ack  kafka writer survive when all the broker are down for a short period. But it should not work this way. So we should not test the case all the servers down

**Comment by KingOfPoptart** [comment]
Add verification that what you expect to happen in the kafka cluster is happening (i.e. assert and print out that a leader change has happened successfully)
