### ISSUE TITLE
[Scribengin] Create the AckKafkaWriter performance test

### ISSUE THREAD

**Issue by tuan08** [DemandCube/NeverwinterDP_Legacy#505]
1. Have look at the current AckKafkaWriterUnitTest and AckKafkaWriterTestRunner
2. extends the AckKafkaWriterTestRunner to support more info such send time , consumed time, sent/s,  consumed/s , message size...
3. Run the performance test with different matrix  message size, num of messages to sent....
4. Any other useful information you can find

**Comment by tuan08** [comment]
Other info such number of partition ,  replication, number of kafka broker , make all them customizable for the runner

**Comment by tuan08** [comment]
Anthony,

My instructions is very clear that you should have look into the AckKafkaWriterUnitTest and AckKafkaWriterTestRunner, update or extend the AckKafkaWriterTestRunner to print out more information...

In order to have a clean and isolate test,  you suppose to run only a test at a time for ex:  send the 100000 messages of 4kb to kafka with the replication = 2, partition = 3 for example, shutdown kafka clean every thing and run another test. Durring the test, you suppose to randomly simulate the failure and the AckKafkaWriterTestRunner is desinged for you to reuse. What is the point to rewrite and have many thread that send the messages(with different configuration) to different topic at the same time.

Your result:

# Broker Configs

## run   expected   written   success   failed   read   Partitions    datasize (KB)   messages/Second   

0     5000       5000      5000      0        5000   1             10              500  
1     5000       5000      5000      0        5000   10            10              500  
2     5000       5000      5000      0        5000   2             100             500  
3     5000       5000      5000      0        5000   20            100             500  
4     5000       5000      5000      0        4250   4             150             500  
5     5000       4885      4885      0        4045   4             200             488               

Has no value.
1.  number of sent messages is too small to create the problem
2. You have many thread that send the data at the same time so kafka or client can be busy on the other.
3. It seems that you send the messages at a fixed rate(every 10ms), how can you tell the different if kafka take 1ms to handle 1kb message and 2ms to handle 10kb messages.
4. Kafka writer cannot send 5000 messages as expected because it is busy on the other test and it does not have enough time due to the max duration limit. Your kafka writer really send 4885 messages and does not loose any messages which is correct here. 
5. The most important part is the failure simulation and you do not work on it. Always start with the most difficult thing , the thing you do not know, you are not sure.... What is the point if you start with the easy work and later you realize that you cannot over come the difficulty, you choose the wrong path due to problem you are not certain how to solve.  You will loose all the work you have started.

The thing I do not understand is why I already make clear that  you should use  AckKafkaWriterTestRunner which is designed and constraint from the mistake and you do not follow.

**Comment by tuan08** [comment]
I check your code again. Due to the way you use the unit test , so  you have the test run  isolated for each configuration. But you should clean and restart kafka to get the cleanest environment. You limit to send the message every 10ms and no failure simulation make the test useless. The test should show that it is reliable as the first goal before showing it performs well.

**Comment by tuan08** [comment]
I always keep repeat that if you have difficulty , you are not certain.   You suppose to ask and I am available most of the time.  One more important goal is to understand and reuse the code. What is the point if I have 2 KafkaMessageSendTool classes. Why do not make one flexible and reusable.

**Comment by anthonyms** [comment]
I was aware that the PerfomanceTest doesn't involve any failure simulation. Just sending many messages to Kafka while changing a few params(message, size, partitions). 
And see how the writer handles such loads.

In my test Kafka is started and stopped before each run.
It runs a test at a time. 
It tests one topic per run. 
The send delay (10ms) is configurable.
Failure simulation is handled in #504 

I have a todo to convert to use your runner.
That commit was end of day work.
