### ISSUE TITLE
vagrant-flow: implement command demandcube-boxes

### ISSUE THREAD

**Issue by smorin** [DemandCube/NeverwinterDP_Legacy#51]
This should list all the cloud shareboxes hosted by demandcube

**Comment by smorin** [comment]
#29 is the parent ticket

**Comment by KingOfPoptart** [comment]
From the Vagrant blog:

```
Coming very soon to Vagrant Cloud: support for organizations, API access, audit logs and statistics for box usage, ACLs on Vagrant Shares, custom domains, and more.
```

I would suggest waiting until the Vagrant Cloud API is released, otherwise any solution to this will be a temporary hack.

**Comment by smorin** [comment]
That makes sense let's postpone this issue but keep it open

**Comment by KingOfPoptart** [comment]
So there's still no capability to just list all the demandcube boxes via the API

https://vagrantcloud.com/docs/boxes

At the moment, you'd be able to list a specific boxes details, but there's no support to list all boxes uploaded by Demandcube.  We can hard code the values to search for (i.e. the box names) but for now I'll mark this as blocked as I find that solution to be wanting.
