### ISSUE TITLE
[Scribengin] Create dev branch, communicate and demonstrate with team the new work flow

### ISSUE THREAD

**Issue by KingOfPoptart** [DemandCube/NeverwinterDP_Legacy#511]

**Comment by KingOfPoptart** [comment]
Also ensure Jenkins is updated to run tests against the new dev branch

**Comment by tuan08** [comment]
It seems that  github does not allow me to create the dev branch , I created dev/master branch  and start working on it. Make sure that all jenkin unit test and integration test use the new branch
