### ISSUE TITLE
[Scribengin] Fix update-hosts command

### ISSUE THREAD

**Issue by KingOfPoptart** [DemandCube/NeverwinterDP_Legacy#513]
tuan08 [2:21 AM] 
@peter: @kingofpoptart  look like the command ./docker.sh container  update-hosts has bug , when /etc/hosts file does not have any vm container entry

tuan08 [2:22 AM]
or  you create 5 kafka server instances first and clean every thing , and recreate with 3 instances

**Comment by jeroldleslie** [comment]
@KingOfPoptart . it need to delete old host entries.
