### ISSUE TITLE
Move the StabilityCheckTool to use the new KafkaTopicCheckTool

### ISSUE THREAD

**Issue by tuan08** [DemandCube/NeverwinterDP_Legacy#519]

**Comment by KingOfPoptart** [comment]
Update kafka.sh in scribengin.release

**Comment by tuan08** [comment]
You suppose to be able to run the AcKafkaWriterUnitTest and AcKafkaWriterPerformanceTest, KafkaTopicCheckToolUnitTest, understand the main parameters you can use and those parameters can be used when you run the real check tool.

To save the time and understand your goal.  You can make a quick run with the  AcKafkaWriterUnitTest to see the sample result you should have when you run in the real docker env.

You can ask Anthony if you have the question since Anthony has some knowledge on this tool.

Remember,  if you really master the tool and kafka ,  you suppose to be able to foresee or predict the result. You just run the test to confirm what you understand
