### ISSUE TITLE
DemandSpike - Create Yarn Application that writes random data to Kafka

### ISSUE THREAD

**Issue by smorin** [DemandCube/NeverwinterDP_Legacy#52]
Get started with Yarn:
http://hortonworks.com/get-started/yarn/

Easiest way to get started with an environment:
http://hortonworks.com/products/hortonworks-sandbox/

**Comment by smorin** [comment]
Commit this to demandspike

**Comment by smorin** [comment]
Please update this ticket with a proposed project design spec

**Comment by KingOfPoptart** [comment]
@louzar what's the status on this?

**Comment by louzar** [comment]
this is done but not merged, Tuan did it in another way

**Comment by KingOfPoptart** [comment]
Thanks @louzar , I'm reassigning this to @tuan08

**Comment by smorin** [comment]
Let's discuss because I want to talk about how we merge the code bases, after the rewrite that Tuan is doing.

**Comment by tuan08** [comment]
I add some document to the DemandSpike README.md, basically  with the new design , we need to implement a yarn app load test  wich will independent from the DemandSpike , a demandspike subcommand to launch the yarn app , maintain the connection with the yarn app to get the status and other information. The yarn app should be laucheable with the builtin yarn or hadoop command and with our custom demandspike command

**Comment by tuan08** [comment]
TODO: move the current DemandSpike code to NeverwinterDP , rename the package name to ringbearer. use  yarn app for demandspike load test.  Integrate demandspike with ringbearer so demandspike can be launched from command line or  ringbearer command
