### ISSUE TITLE
[Sribengin] Create more dataflow test to run in Cluster -> hdfs source to hdfs sink

### ISSUE THREAD

**Issue by tuan08** [DemandCube/NeverwinterDP_Legacy#521]
We need to create more dataflow test and check tool. The example of the dataflow test are:
- Input from from hdfs  source, output to hdfs sink
- Input from from hdfs  source, output to kafka sink
- Input from from kafka source, output to hdfs sink.

Nizar or Anthony can pick up this test

**Comment by tuan08** [comment]
See #520 and KafkaDataflowTest to see how to setup a Dataflow test

**Comment by KingOfPoptart** [comment]
Focus on hdfs -> hdfs

Look at ScribenginSingleJVMUnitTest for how to implement - have it run on the docker cluster using the command line.
