### ISSUE TITLE
DemandSpike - Create Yarn Application Kafka Load Testing Framework

### ISSUE THREAD

**Issue by smorin** [DemandCube/NeverwinterDP_Legacy#53]
Create application that has aggregated metrics

Total Events Written
Total Bytes Written

**Comment by KingOfPoptart** [comment]
@louzar Have you started/worked on this?

**Comment by smorin** [comment]
Nizar where is the link to the pull request?

**Comment by louzar** [comment]
Same thing as issue #54,  pull request is here https://github.com/DemandCube/DemandSpike/pull/2/files
Since that Tuan merged his code into DemandSpike, I forked demandSpike again from demandCube/demandspike and move it my source code to https://github.com/louzar/DemandSpikeOld
