### ISSUE TITLE
DemandSpike - Create Yarn Application Kafka Load Testing Framework Part 2

### ISSUE THREAD

**Issue by smorin** [DemandCube/NeverwinterDP_Legacy#54]
Create application that has aggregated metrics

Events by Second
Bytes by Second

Report of events by second aggregated and by individual producer.

**Comment by KingOfPoptart** [comment]
@louzar status on this issue?

**Comment by smorin** [comment]
Where is the link to the pull request?

**Comment by louzar** [comment]
pull request is here https://github.com/DemandCube/DemandSpike/pull/2/files.
Since that Tuan merged his code into DemandSpike, I forked demandSpike again from demandCube/demandspike and move it my source code to https://github.com/louzar/DemandSpikeOld

**Comment by louzar** [comment]
I think this issue can be closed if we don't need https://github.com/louzar/DemandSpikeOld
