### ISSUE TITLE
[Scribengin] Un-deprecate KafkaTool.deleteTopic()

### ISSUE THREAD

**Issue by anthonyms** [DemandCube/NeverwinterDP_Legacy#544]
Use TopicCommand.deleteTopic instead of AdminUtils.deleteTopic()

Also ensure cluster has "delete.topic.enable" = "true"

More Info:
https://issues.apache.org/jira/browse/KAFKA-1397
http://blog.confluent.io/2014/12/02/whats-coming-in-apache-kafka-0-8-2/

**Comment by anthonyms** [comment]
in view of the discussion here http://search-hadoop.com/m/4TaT4VWNg8/v=plain

The task changes to
1. Un-deprecate the method
2. Add "delete.topic.enable" = "true" to the cluster
3. Add a warning in checktopic() to warn caller of topics that exists but are scheduled for deletion.

**Comment by KingOfPoptart** [comment]
Great work on getting more info, @artfullyContrived !

Where is checktopic() in the code?

**Comment by anthonyms** [comment]
Thanks.
Should be topicExists() not checkTopic() in KafkaTool.
