### ISSUE TITLE
DemandSpike Alpha Architecture Plan

### ISSUE THREAD

**Issue by smorin** [DemandCube/NeverwinterDP_Legacy#55]
Create a Plan for the Alpha version of a generic load testing framework using Yarn

Should have 3 parts.
1) Run a load test without Yarn (Single Instance/Machine)
2) Run a load test with Yarn in Batch Mode
3) Run a continous load test with Yarn till Application master in told to stop.  Should give continous metrics and integrate with a solution like Yammer metrics library or maybe use the solution Kafka has.  Needs to also integrate with JMX Trans or other solution - Ganglie Graphite

This project is meant to be a distributed load testing framework like:
http://tsung.erlang-projects.org/

It should always measure:
- Volume (number of events)
- IO (Size of the data being sent)
- Latency (Time to send an event)
- Error (Number of error or failures)

All should have:
By Second and Total
(min, max, average, 90 95 98 and 99th percentiles)

**Comment by KingOfPoptart** [comment]
@louzar What's the status on this?  Is this part of your work with Demandspike?
