### ISSUE TITLE
Integrate JMX Trans with Kafka

### ISSUE THREAD

**Issue by smorin** [DemandCube/NeverwinterDP_Legacy#56]
This means
1) Ansible Scripts to Install JMX Trans 
2) Scripts and documentation to start running JMX Trans
3) Documented Instructions on how to use JMX Trans
4) Script to list all the Metrics that are possible to get from Kafka and the return types
5) Create tests to validate the ansible install worked (coordinate with @KingOfPoptart )

**Comment by anthonyms** [comment]
Started.

@smorin 
Got a jmxtrans json that provides all kafka metrics but how do I get their return types?
See https://kafka.apache.org/documentation.html#monitoring.

**Comment by smorin** [comment]
@mjuaji SO you have a working example?  I don't know how you get the return types, you'll have to research that.  You might have to write a JMX helper utility that will return all metrics and their return types.

@KingOfPoptart @mehikmat @mjuaji @noitcudni Do you think we should have a new repo just for helper utilities?  How do you think we should organize that?  Example should we have a repo per utility?

**Comment by anthonyms** [comment]
I use a basic json file that captures the Mbeans in the following categories
    kafka.consumer:*
    kafka.controller:*
    kafka.log:*
    kafka.network:*
    kafka.server:*

It presents info e.g.
127_0_0_1_9999.kafka.controller.StdDev  0.0     1396359990847
127_0_0_1_9999.kafka.controller.Mean    0.0     1396359990847
127_0_0_1_9999.kafka.controller.Min     0.0     1396359990847
127_0_0_1_9999.kafka.controller.50thPercentile  0.0     1396359990847
127_0_0_1_9999.kafka.controller.99thPercentile  0.0     1396359990847
127_0_0_1_9999.kafka.controller.999thPercentile 0.0     1396359990847
127_0_0_1_9999.kafka.controller.MeanRate        0.0     1396359990859
127_0_0_1_9999.kafka.controller.OneMinuteRate   0.0     1396359990859
127_0_0_1_9999.kafka.controller.FiveMinuteRate  0.0     1396359990859
127_0_0_1_9999.kafka.controller.FifteenMinuteRate       0.0
1396359990859
127_0_0_1_9999.kafka.controller.Count   0       1396359990859

Ill read up some more and update the team.

**Comment by smorin** [comment]
Please do.  Also open up an issue to develop a utility to print out all JMX
Metrics and their keys.

On Tue, Apr 1, 2014 at 6:49 AM, artfullyContrived
notifications@github.comwrote:

> I use a basic json file that captures the Mbeans in the following
> categories
> kafka.consumer:*
> kafka.controller:*
> kafka.log:*
> kafka.network:*
> kafka.server:*
> 
> It presents info e.g.
> 127_0_0_1_9999.kafka.controller.StdDev 0.0 1396359990847
> 127_0_0_1_9999.kafka.controller.Mean 0.0 1396359990847
> 127_0_0_1_9999.kafka.controller.Min 0.0 1396359990847
> 127_0_0_1_9999.kafka.controller.50thPercentile 0.0 1396359990847
> 127_0_0_1_9999.kafka.controller.99thPercentile 0.0 1396359990847
> 127_0_0_1_9999.kafka.controller.999thPercentile 0.0 1396359990847
> 127_0_0_1_9999.kafka.controller.MeanRate 0.0 1396359990859
> 127_0_0_1_9999.kafka.controller.OneMinuteRate 0.0 1396359990859
> 127_0_0_1_9999.kafka.controller.FiveMinuteRate 0.0 1396359990859
> 127_0_0_1_9999.kafka.controller.FifteenMinuteRate 0.0
> 1396359990859
> 127_0_0_1_9999.kafka.controller.Count 0 1396359990859
> 
> Ill read up some more and update the team.
> 
> On Tue, Apr 1, 2014 at 4:38 PM, Steve Morin <notifications@github.com
> 
> > wrote:
> > 
> > @mjuaji https://github.com/mjuaji SO you have a working example? I
> > don't know how you get the return types, you'll have to research that.
> > You
> > might have to write a JMX helper utility that will return all metrics and
> > their return types.
> > 
> > @KingOfPoptart https://github.com/KingOfPoptart @mehikmat<
> > https://github.com/mehikmat>
> > @mjuaji https://github.com/mjuaji @noitcudni<
> > https://github.com/noitcudni>Do you think we should have a new repo just
> > for helper utilities? How do
> > you think we should organize that? Example should we have a repo per
> > utility?
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub<
> > https://github.com/DemandCube/NeverwinterDP/issues/56#issuecomment-39205850
> > 
> > .
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/DemandCube/NeverwinterDP/issues/56#issuecomment-39207056
> .

## 

Steve Morin | Hacker, Entrepreneur, Startup Advisor
twitter.com/SteveMorin | stevemorin.com
_Live the dream start a startup. Make the world ... a better place._

**Comment by smorin** [comment]
Since this is in code review please put the link to the pull request in the ticket.

**Comment by mehikmat** [comment]
@mjuaji  please put url of pull request here so that I can review

**Comment by anthonyms** [comment]
@mehikmat This is already being reviewed by @noitcudni but here is the pull request nevertheless
https://github.com/DemandCube/DeveloperPlayBooks/pull/2

**Comment by mehikmat** [comment]
@mjuaji Okay if @noitcudni is reviewing, that's fine.

**Comment by KingOfPoptart** [comment]
I don't think a repo of dev tools would be terrible.  I was actually thinking of writing a tool to help us manage merging code into github, so that https://github.com/DemandCube/NeverwinterDP/blob/master/README.md#git-workflow-to-develop-a-new-feature  becomes less of a cumbersome process

**Comment by smorin** [comment]
@KingOfPoptart what did you have in mind for the utils.  I was thinking that we would make them all pip executables

**Comment by KingOfPoptart** [comment]
PIP would be good since it would encourage people to use Python!

**Comment by smorin** [comment]
Yes pip would be good

On Mon, Apr 21, 2014 at 3:17 PM, Richard Duarte notifications@github.comwrote:

> PIP would be good since it would encourage people to use Python!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/DemandCube/NeverwinterDP/issues/56#issuecomment-40983545
> .

## 

Steve Morin | Hacker, Entrepreneur, Startup Advisor
twitter.com/SteveMorin | stevemorin.com
_Live the dream start a startup. Make the world ... a better place._
