### ISSUE TITLE
[Scribengin] Implement DataflowSinkValidator and DataSourceGenerator for hdfs

### ISSUE THREAD

**Issue by tuan08** [DemandCube/NeverwinterDP_Legacy#572]
Need to implement the  DataflowSinkValidator and DataSourceGenerator  for HDFS and S3. Maybe S3 later.
Need to reuse the DataflowTestReport as well.

Since HDFS and S3 is the batch storage, which mean that you have to wait until you finish generating the data before you can submit the dataflow. It also means you cannot run the generator in a separated thread and use waitForTermination... But need to implement those method to  keep it compatible with the interface.

Implement junit report in DataflowTestReport like the way KafkaTopicReport implement.

**Comment by KingOfPoptart** [comment]
Focus on just HDFS for now

**Comment by KingOfPoptart** [comment]
Extend DataflowSourceGenerator

Add options to DataflowSourceGenerator - 
--record-size
