### ISSUE TITLE
Study the HDFS source/sink

### ISSUE THREAD

**Issue by jeroldleslie** [DemandCube/NeverwinterDP_Legacy#577]

**Comment by tuan08** [comment]
1. You need to setup aws as describe in S3FeaturesDemoTest and able to run it 
2. Look into that test to see what you can do with S3
3. Look into S3SinkSourceIntegrationTest. The S3Source is not implemented yet, you need to implement it like HDFSSource and create a test like  HDFSSinkSourceUnitTest
