### ISSUE TITLE
Jenkins - Analyze test failures and fix them or submit tickets for bugs for what is blocking

### ISSUE THREAD

**Issue by KingOfPoptart** [DemandCube/NeverwinterDP_Legacy#579]
http://jenkinsdp.do.demandcube.com:8080/view/Integration%20Tests%20Dev/

Two of the tests are outright causing a failure (red dot = something wrong with the test) (HDFS to HDFS and HDFS to Kafka)

The rest of the tests are reporting test failure in the test report.  Figure out what issue is causing them and either fix them or write up bugs on what is wrong and what needs to be done to fix them.

Update the team on slack with your findings

**Comment by anthonyms** [comment]
related to #581
