### ISSUE TITLE
Update clustercommander to be able to execute arbitrary commands on all servers

### ISSUE THREAD

**Issue by KingOfPoptart** [DemandCube/NeverwinterDP_Legacy#612]
Currently to execute a command on all machines in the cluster we run 

```
./cluster.sh exec "blahblah"
```

Update cluster commander to be able to do the same

```
python clusterCommander.py exec "blahblah"
```

Update the readme to reflect these changes: https://github.com/DemandCube/Scribengin/tree/dev/master/V2/docker/scribengin

**Comment by jeroldleslie** [comment]
exec is a keywword in python it is not able to use. so --execute option is added under master command "cluster". so exec command is like 

```
python clusterCommander.py cluster --execute "blahblah"
```

**Comment by KingOfPoptart** [comment]
No problem, that sounds fine
