### ISSUE TITLE
clusterComander.py cluster --execute "blahblah" doesn't output anything

### ISSUE THREAD

**Issue by KingOfPoptart** [DemandCube/NeverwinterDP_Legacy#618]
```
rcduar@appleTarts:cluster $ ./clusterCommander.py  cluster --execute "ls -la /opt"
rcduar@appleTarts:cluster $
```

This command should print out STDOUT and STDERR from whatever gets executed, and it should say which machine the results are from

**Comment by jeroldleslie** [comment]
This was done
Output will look like

---

Executing 'ls -la /opt' on hadoop-master

---

total 44
drwxr-xr-x  19 neverwinterdp neverwinterdp  4096 Apr 13 12:38 .
drwxr-xr-x 170 root          root           4096 Apr 13 12:37 ..
drwxr-xr-x  10 neverwinterdp neverwinterdp  4096 Apr 13 12:38 cluster
-rwxr-xr-x   1 neverwinterdp neverwinterdp 13439 Apr 13 12:34 cluster.sh
drwxr-xr-x  19 neverwinterdp neverwinterdp  4096 Apr 14 09:13 hadoop
drwxr-xr-x   8 neverwinterdp neverwinterdp  4096 Apr 13 12:34 kafka
drwxr-xr-x   5 neverwinterdp neverwinterdp  4096 Apr 13 12:35 scribengin
drwxr-xr-x  19 neverwinterdp neverwinterdp  4096 Apr 13 12:34 zookeeper

---
