### ISSUE TITLE
clustercommander - hadoop --start -> NameNode won't start without using --clean option

### ISSUE THREAD

**Issue by KingOfPoptart** [DemandCube/NeverwinterDP_Legacy#620]
Try running on a clean installation (i.e. bring up new docker images)

```
./clusterCommander.py hadoop --start status
```

When I do that, namenode doesn't seem to start

```
Role           Hostname         ProcessIdentifier    ProcessID    HomeDir         Status
-------------  ---------------  -------------------  -----------  --------------  --------
hadoop-master  hadoop-master
                                NameNode                          /opt/hadoop     None
                                SecondaryNameNode    1815         /opt/hadoop     Running
                                ResourceManager      1918         /opt/hadoop     Running
```

The only way to get it to work is by running

```
./clustercommander.py hadoop --start --clean
```

**Comment by jeroldleslie** [comment]
Actually --clean will delete datas and format namenode. In hadoop namenode should be formated at the first time before starting the hadoop cluster. so if we are running the hadoop cluster first time it is mandatory to run --clean option.

**Comment by KingOfPoptart** [comment]
Then we need to have a check to see if its the first time starting hadoop and run clean first, 

or do something after start() has completed that checks if the namenode successfully started - if its failed then run restart() clean()
