### ISSUE TITLE
Setup and Install unhangout on hangout.demandcube.com

### ISSUE THREAD

**Issue by smorin** [DemandCube/NeverwinterDP_Legacy#63]
Install Unhangout on our server
1) Document The Installation Process
2) Put the process into Ansible to be deployable
3) Create test scripts to monitor that it's running. (Talk with Richard)

The install should be an Ansible Role Role/Unhangout

This Role should use Ansible Best Practices
http://docs.ansible.com/playbooks_best_practices.html

The role should be saved in the Repository 
https://github.com/DemandCube/DemandCubePlaybooks

https://unhangout.media.mit.edu/about/
https://github.com/drewww/unhangout

**Comment by smorin** [comment]
Figured out a simpler method for this and am opening a new ticket for that method.  This might be better when we want to give open classes on the project in the future.

**Comment by anthonyms** [comment]
@smorin 
Should this issue be closed?

**Comment by smorin** [comment]
@mjuaji might use this in the future so I moved it the backlog milestone
