### ISSUE TITLE
vagrant-flow: command playbook and .playbook file

### ISSUE THREAD

**Issue by smorin** [DemandCube/NeverwinterDP_Legacy#64]
Implement it so that if you issue a vagrant playbook it tries to run a playbook based on defaults.
- playbook -> try to run a default playbook and inventory file specificed in .playbook  if exists

**Comment by smorin** [comment]
Parent is #29

**Comment by KingOfPoptart** [comment]
Steve, could you be more verbose on the requirements here?

Is this meant to influence the vagrant default ansible provisioner, or is this meant to influence the ansible-inventory command?

i.e.
.playbook

```
---
:playbook: ../defaultplaybook.yml
:inventory: ../defaultinventory.file
```

and then we run 

```
vagrant flow playbook
```

The flow playbook command will automatically invoke

```
ansible-playbook -i ../defaultinventory.file ../defaultplaybook.yml
```

**Comment by smorin** [comment]
`vagrant flow playbook` is a convience command so that it's easier to run `ansible-playbook`  It's meant to read from a config file to get it's basic setting so you can run it easily.

`vagrant flow playbook [hostpattern for ansible] [-f "path to config file that's yml]`

If "hostpattern for ansible" isn't specified it should default to "all"
If "-f "path to config file that's yml" isn't specified it should use some sort of default file name"

I haven't though of what the config file name should be but guessed .playbook might work or clearer would be flow-playbook.yml.  It should look for this file in the current directory unless you set the commandline argument.  Paths in the config should be absolute or relative from where the config file exists.  Figure since everything else is yml file format should be yml.  I haven't thought what the structure or name of the variables/settings in the file should be.

Should looks at some default config file to set two variables

1) defaultinventory file path
2) defaultplaybook file path
3) Maybe optional 3rd variable to set the "hostpattern"

defaultinventory.file = "name from vagrant flow ansible-inventory"
defaultplaybook

`ansible-playbook [pattern] -i ../defaultinventory.file ../defaultplaybook.yml`

**Comment by smorin** [comment]
For debugging and as a template, it would be nice if `vagrant flow -p`  The -p setting would make it print the command it would execute without executing it.

**Comment by KingOfPoptart** [comment]
Merge requested
https://github.com/DemandCube/vagrant-flow/pull/7

**Comment by KingOfPoptart** [comment]
Merged
