### ISSUE TITLE
KafkaSphere Alpha Milestone Planning

### ISSUE THREAD

**Issue by smorin** [DemandCube/NeverwinterDP_Legacy#65]
This is the initial version of KafkaSphere Rest API
- Week 1  
  - Development Env. / Learning Ansible & Vagrant
    - Finished by Mar 25 (tuesday)
    - NeverwinterDP (https://github.com/DemandCube/NeverwinterDP)
- Week 2
  - Propose initial functionality based on
    - https://github.com/DemandCube/NeverwinterDP/issues/43
    - https://github.com/claudemamo/kafka-web-console
    - http://quantifind.com/KafkaOffsetMonitor/
  - Your not going todo it all at once to each of you pick the smallest piece possible todo and create a ticket for it and the following two tickets. All in tickets: Research -> Design of API-> Design Tests -> Code Tests for X -> Code X 
    - e.g. will Jesse plan the requirements for the Brokers? and Sam plan requirement for Zookeepers etc ...
  - Mentor Check-in w/ Steve @ Midweek 
    - Are we on the right track for the scope?
  - What kind of endpoints do we want?
    - These will be flexibly named? 
      - Swagger might be a good utility here
  - What data do we want to access @ the endpoints
    - Testing data, etc…
  - TDD 
    - What will we be testing for?
- Week 3
  - Up to speed with:
    - Java
    - Spark (http://www.sparkjava.com/)
    - Team organization & breakdown 
- Week 4, 5 & 6 - Crafting Sprint (ends May 1)
  - Quickly rescope
  - Begin building the API
  - End-to-end tests

**Comment by smorin** [comment]
Also please refer to #43

**Comment by KingOfPoptart** [comment]
Can we close this issue?
