### ISSUE TITLE
Playbooks Testing Framework - Plan and Strategy

### ISSUE THREAD

**Issue by smorin** [DemandCube/NeverwinterDP_Legacy#67]
Given that we are creating Roles to install software using:

```
  https://github.com/DemandCube/DemandCubePlaybooks
  https://github.com/DemandCube/DeveloperCubePlaybooks
```

We NEED a testing strategy.

This ticket is to:
1) Come up with a testing strategy
2) Create all the tickets to develop that plan for the team.

The Goal:
  We have automated and comprehensive testing of the playbooks.  What is the easiest way to maintain this goal

The possible options:
  Create tests in the ansible playbooks themselves
  Have separate tests that are created in nose and tested with github hooks into Jenkins
  A combination of these things.

**Comment by KingOfPoptart** [comment]
Testing strategy for roles will be to expand our installation_tests.  Continuous Integration will follow

https://github.com/DemandCube/QA-NeverwinterDP/tree/master/installation_tests
