### ISSUE TITLE
Java Application to Write to Random Bytes Kafka

### ISSUE THREAD

**Issue by smorin** [DemandCube/NeverwinterDP_Legacy#69]

**Comment by smorin** [comment]
@louzar can you add a reference to the repo where this code lives

**Comment by louzar** [comment]
I added a repository under my github account, because it won't allow me on demande Cube 
https://github.com/louzar/DemandCube

**Comment by smorin** [comment]
If you want a new repo you have to request that I create it, for this
starting work keep it in your personal repo.  When we have a plan for the
testing framework we'll move it to DemandSpike.

On Mon, Apr 7, 2014 at 3:06 AM, Nizar notifications@github.com wrote:

> I added a repository under my github account, because it won't allow me on
> demande Cube
> https://github.com/louzar/DemandCube
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/DemandCube/NeverwinterDP/issues/69#issuecomment-39713894
> .

## 

Steve Morin | Hacker, Entrepreneur, Startup Advisor
twitter.com/SteveMorin | stevemorin.com
_Live the dream start a startup. Make the world ... a better place._

**Comment by louzar** [comment]
ok great

**Comment by smorin** [comment]
@louzar Since this is in code review please put the link to the pull request in the ticket.  Merge this into DemandSpike because this should be initial code for it.

**Comment by louzar** [comment]
I could'nt push to DemandSpike repo, I think I don't have permission

**Comment by smorin** [comment]
You have to for and do a pull request

**Comment by smorin** [comment]
Please put the pull request in this ticket

**Comment by louzar** [comment]
pull request : https://github.com/DemandCube/DemandSpike/pull/1
