### ISSUE TITLE
Refactor code to allow to reuse  the old neverwinterdp in a better way.

### ISSUE THREAD

**Issue by tuan08** [DemandCube/NeverwinterDP_Legacy#717]
In order to better organize the code to be developed, built and deployed, I proposed a new project structure as follow:

```
nventdata
  lib/
    commons
    yara
    buffer

  module
    kafka
    elasticsearch
    yara-server

  registry
    core
    vm
      core
      single-jvm
      yarm

  demandspike

  sparkngin

  queungin

  scribengin
    core
    dataflows
      sample-kafka
      sample-hdfs
      sample-s3
      log-demo
    release

  client
     shell
       core
       vm
       scribengin
     swingui
       core
       scribengin
       elasticsearch

  tools
    cluster
```
- lib: The lib directory contains the basic and core library such utility to process the text , file , json, metrics....
- module: The module directory contains the project that can act as a standalone service or server such kafka, elasticsearch....
- registry: Is our developed code. The registry contains the core project and several other subproject such vm core project that implement on top of the registry core, and the other implementation for vm core such single-jvm for testing ,  yarn...
- scribengin, demandspike, sparkngin, queuengin are our developed code and they should have a core project and other sub project to add more features to the core.
- client:  is our developed code. We can have different type of client such text base(shell) , ui (swingui, webui). As usually , we should have a core project for each type and different plugin for the specific project. For ex:  scribengin plugin for shell , swingui 

@smorin @KingOfPoptart

**Comment by KingOfPoptart** [comment]
demandspike,  sparkngin,  queuengin  will not be moved currently.  It will be moved sometime in the future when we start working on them again.

**Comment by tuan08** [comment]
Yes the structure is designed for later upgrade or refactor

**Comment by tuan08** [comment]
The client will be refactor later , well the project is getting bigger and more complicated
