### ISSUE TITLE
Create installation verification tests for all programs and roles in DemandCubePlaybooks

### ISSUE THREAD

**Issue by KingOfPoptart** [DemandCube/NeverwinterDP_Legacy#72]
Expand: https://github.com/DemandCube/QA-NeverwinterDP/tree/master/installation_tests

Create a new role for each and every program and role not currently covered by the installation tests
# To do this:

Each ticket should have at least one (It could require more than one) additional file in the role directory of installation_tests
# To figure out what kind of test is required:

Review https://github.com/DemandCube/DemandCubePlaybooks
Each ticket will correspond to either a program or a role.  Figure out a good way to ensure that a component is installed by checking if the binary exists, if the version is correct, a service is running, a file exists, a Python module is installed, or by creating a new verification method.
# To fully complete this task:
- Integrate these tests into Jenkins
- Ensure whenever anyone does a push, the tests are run
- Ensure whenever there is a pull request, the tests are run

**Comment by KingOfPoptart** [comment]
@louzar isn't this done?  I think this was a super-ticket for a bunch of sub tasks

*Edit - never mind, there's a bunch of open tickets still as sub tasks

**Comment by louzar** [comment]
some of done verification test check the version, which one of the remaining components should be version tested

**Comment by smorin** [comment]
Email Richard directly

**Comment by louzar** [comment]
ok, another thing, in case we need to check to version or the existence of a file, we need to get its value from the DemandCubePlaybooks project. For example if we want to test if kafka web console is installed we need to know its path from https://github.com/DemandCube/DemandCubePlaybooks/blob/master/roles/kafka-web-console/tasks/main.yml, so the verification test script depend sometimes from the DemandCubePlaybooks
