### ISSUE TITLE
Create test for git-daemon

### ISSUE THREAD

**Issue by KingOfPoptart** [DemandCube/NeverwinterDP_Legacy#74]

**Comment by KingOfPoptart** [comment]
Parent is https://github.com/DemandCube/NeverwinterDP/issues/72

**Comment by KingOfPoptart** [comment]
Parent is https://github.com/DemandCube/NeverwinterDP/issues/72

**Comment by louzar** [comment]
pull request : https://github.com/DemandCube/QA-NeverwinterDP/pull/18
