### ISSUE TITLE
Create test for kafka-offset-monitor

### ISSUE THREAD

**Issue by KingOfPoptart** [DemandCube/NeverwinterDP_Legacy#82]

**Comment by KingOfPoptart** [comment]
Parent is https://github.com/DemandCube/NeverwinterDP/issues/72

**Comment by smorin** [comment]
Since this is in code review please put the link to the pull request in the ticket.

**Comment by anthonyms** [comment]
Here it is
https://github.com/DemandCube/QA-NeverwinterDP/pull/8
