### ISSUE TITLE
Create test for zookeeper_test

### ISSUE THREAD

**Issue by KingOfPoptart** [DemandCube/NeverwinterDP_Legacy#91]

**Comment by KingOfPoptart** [comment]
Parent is https://github.com/DemandCube/NeverwinterDP/issues/72

**Comment by louzar** [comment]
could you give more details, what's zookeeper_test  and what should be tested

**Comment by KingOfPoptart** [comment]
Actually it looks like zookeeper_test was a prototype for the zookeeper role.

Go ahead and skip writing a test for this.
