### ISSUE TITLE
Update developerSetup_config.py

### ISSUE THREAD

**Issue by KingOfPoptart** [DemandCube/NeverwinterDP_Legacy#93]
Parent is #92

**Comment by KingOfPoptart** [comment]
This should work on a Mac and Ubuntu. Look at the sections in the parent script on how to test for a Mac. Make sure the scripts work on ubuntu.

**Comment by louzar** [comment]
there is no host for developer setup in https://github.com/DemandCube/DemandCubePlaybooks/blob/master/main.yml, do you mean common host
